namespace TadbirTaxService.Models.Intamedia
{
    public class IntamediaCity
    {
        public string Code { get; set; }
        public string Name { get; set; }

        public static List<IntamediaCity> Cities
        {
            get
            {
                return [
                    new IntamediaCity() { Code = "1", Name = "آذر شهر" },
                    new IntamediaCity() { Code = "2", Name = "گوگان" },
                    new IntamediaCity() { Code = "3", Name = "ممقان" },
                    new IntamediaCity() { Code = "4", Name = "بستان آباد" },
                    new IntamediaCity() { Code = "9", Name = "تیکمه داش" },
                    new IntamediaCity() { Code = "10", Name = "بناب" },
                    new IntamediaCity() { Code = "11", Name = "باسمنج" },
                    new IntamediaCity() { Code = "12", Name = "تبریز" },
                    new IntamediaCity() { Code = "13", Name = "خسرو شهر" },
                    new IntamediaCity() { Code = "14", Name = "سردرود" },
                    new IntamediaCity() { Code = "15", Name = "جلفا" },
                    new IntamediaCity() { Code = "16", Name = "سیه رود" },
                    new IntamediaCity() { Code = "17", Name = "هادیشهر" },
                    new IntamediaCity() { Code = "18", Name = "قره آغاج" },
                    new IntamediaCity() { Code = "19", Name = "دوزدوزان" },
                    new IntamediaCity() { Code = "20", Name = "سراب" },
                    new IntamediaCity() { Code = "21", Name = "شربیان" },
                    new IntamediaCity() { Code = "22", Name = "مهربان" },
                    new IntamediaCity() { Code = "23", Name = "تسوج" },
                    new IntamediaCity() { Code = "24", Name = "خامنه" },
                    new IntamediaCity() { Code = "25", Name = "سیس" },
                    new IntamediaCity() { Code = "26", Name = "شبستر" },
                    new IntamediaCity() { Code = "27", Name = "شرفخانه" },
                    new IntamediaCity() { Code = "28", Name = "شند آباد" },
                    new IntamediaCity() { Code = "29", Name = "صوفیان" },
                    new IntamediaCity() { Code = "31", Name = "وایقان" },
                    new IntamediaCity() { Code = "32", Name = "عجب شیر" },
                    new IntamediaCity() { Code = "33", Name = "کلیبر" },
                    new IntamediaCity() { Code = "34", Name = "آبش احمد" },
                    new IntamediaCity() { Code = "35", Name = "خمارلو" },
                    new IntamediaCity() { Code = "36", Name = "خداجو" },
                    new IntamediaCity() { Code = "37", Name = "مراغه" },
                    new IntamediaCity() { Code = "38", Name = "بناب جدید" },
                    new IntamediaCity() { Code = "39", Name = "زنوز" },
                    new IntamediaCity() { Code = "40", Name = "کشکسرای" },
                    new IntamediaCity() { Code = "41", Name = "مرند" },
                    new IntamediaCity() { Code = "42", Name = "یامچی" },
                    new IntamediaCity() { Code = "43", Name = "لیلان" },
                    new IntamediaCity() { Code = "44", Name = "ملکان" },
                    new IntamediaCity() { Code = "45", Name = "آقکند" },
                    new IntamediaCity() { Code = "46", Name = "ترک" },
                    new IntamediaCity() { Code = "47", Name = "ترکمانچای" },
                    new IntamediaCity() { Code = "48", Name = "میانه" },
                    new IntamediaCity() { Code = "49", Name = "خاروانا" },
                    new IntamediaCity() { Code = "50", Name = "ورزقان" },
                    new IntamediaCity() { Code = "51", Name = "بخشایش" },
                    new IntamediaCity() { Code = "52", Name = "خواجه" },
                    new IntamediaCity() { Code = "53", Name = "زرنق" },
                    new IntamediaCity() { Code = "55", Name = "هریس" },
                    new IntamediaCity() { Code = "56", Name = "نظر کهریزی" },
                    new IntamediaCity() { Code = "57", Name = "هشترود" },
                    new IntamediaCity() { Code = "58", Name = "گندمان" },
                    new IntamediaCity() { Code = "59", Name = "بروجن" },
                    new IntamediaCity() { Code = "60", Name = "فرادنبه" },
                    new IntamediaCity() { Code = "61", Name = "سفید دشت" },
                    new IntamediaCity() { Code = "62", Name = "بلداجی" },
                    new IntamediaCity() { Code = "63", Name = "شلمزار" },
                    new IntamediaCity() { Code = "64", Name = "گهرو" },
                    new IntamediaCity() { Code = "65", Name = "شهر کرد" },
                    new IntamediaCity() { Code = "66", Name = "فرخ شهر" },
                    new IntamediaCity() { Code = "67", Name = "هفشجان" },
                    new IntamediaCity() { Code = "68", Name = "کیان" },
                    new IntamediaCity() { Code = "69", Name = "طاقانک" },
                    new IntamediaCity() { Code = "70", Name = "نافچ" },
                    new IntamediaCity() { Code = "71", Name = "بن" },
                    new IntamediaCity() { Code = "72", Name = "سامان" },
                    new IntamediaCity() { Code = "73", Name = "سورشجان" },
                    new IntamediaCity() { Code = "74", Name = "سودجان" },
                    new IntamediaCity() { Code = "75", Name = "جونقان" },
                    new IntamediaCity() { Code = "76", Name = "فارسان" },
                    new IntamediaCity() { Code = "77", Name = "باباحیدر" },
                    new IntamediaCity() { Code = "78", Name = "مال خلیفه" },
                    new IntamediaCity() { Code = "79", Name = "لردگان" },
                    new IntamediaCity() { Code = "80", Name = "الونی" },
                    new IntamediaCity() { Code = "81", Name = "اردل" },
                    new IntamediaCity() { Code = "82", Name = "ناغان" },
                    new IntamediaCity() { Code = "83", Name = "چلگرد" },
                    new IntamediaCity() { Code = "84", Name = "ازنا" },
                    new IntamediaCity() { Code = "85", Name = "مومن آباد" },
                    new IntamediaCity() { Code = "86", Name = "الیگودرز" },
                    new IntamediaCity() { Code = "87", Name = "اشترینان" },
                    new IntamediaCity() { Code = "88", Name = "بروجرد" },
                    new IntamediaCity() { Code = "89", Name = "پلدختر" },
                    new IntamediaCity() { Code = "90", Name = "معمولان" },
                    new IntamediaCity() { Code = "91", Name = "بیرانوند" },
                    new IntamediaCity() { Code = "92", Name = "خرم آباد" },
                    new IntamediaCity() { Code = "93", Name = "زاغه" },
                    new IntamediaCity() { Code = "94", Name = "سپید دشت" },
                    new IntamediaCity() { Code = "95", Name = "سرابدوره" },
                    new IntamediaCity() { Code = "97", Name = "نورآباد" },
                    new IntamediaCity() { Code = "98", Name = "چالانچولان" },
                    new IntamediaCity() { Code = "99", Name = "دورود" },
                    new IntamediaCity() { Code = "100", Name = "الشتر" },
                    new IntamediaCity() { Code = "101", Name = "فیروز آباد" },
                    new IntamediaCity() { Code = "102", Name = "چقابل" },
                    new IntamediaCity() { Code = "103", Name = "درب گنبد" },
                    new IntamediaCity() { Code = "104", Name = "کونانی" },
                    new IntamediaCity() { Code = "105", Name = "کوهدشت" },
                    new IntamediaCity() { Code = "106", Name = "گراب" },
                    new IntamediaCity() { Code = "107", Name = "اسدآباد" },
                    new IntamediaCity() { Code = "108", Name = "بهار" },
                    new IntamediaCity() { Code = "109", Name = "صالح آباد" },
                    new IntamediaCity() { Code = "110", Name = "لالجین" },
                    new IntamediaCity() { Code = "111", Name = "تویسرکان" },
                    new IntamediaCity() { Code = "112", Name = "سرکان" },
                    new IntamediaCity() { Code = "113", Name = "فرسفج" },
                    new IntamediaCity() { Code = "114", Name = "دمق" },
                    new IntamediaCity() { Code = "115", Name = "رزن" },
                    new IntamediaCity() { Code = "116", Name = "قروه درجزین" },
                    new IntamediaCity() { Code = "117", Name = "شیرین سو" },
                    new IntamediaCity() { Code = "118", Name = "کبودرآهنگ" },
                    new IntamediaCity() { Code = "119", Name = "گل تپه" },
                    new IntamediaCity() { Code = "120", Name = "ازندریان" },
                    new IntamediaCity() { Code = "121", Name = "جوکار" },
                    new IntamediaCity() { Code = "122", Name = "زنگنه" },
                    new IntamediaCity() { Code = "123", Name = "سامن" },
                    new IntamediaCity() { Code = "124", Name = "ملایر" },
                    new IntamediaCity() { Code = "125", Name = "میراباد" },
                    new IntamediaCity() { Code = "126", Name = "فیروزان" },
                    new IntamediaCity() { Code = "127", Name = "گیان" },
                    new IntamediaCity() { Code = "128", Name = "نهاوند" },
                    new IntamediaCity() { Code = "129", Name = "جورقان" },
                    new IntamediaCity() { Code = "130", Name = "فامنین" },
                    new IntamediaCity() { Code = "131", Name = "قهاوند" },
                    new IntamediaCity() { Code = "132", Name = "مریانج" },
                    new IntamediaCity() { Code = "133", Name = "همدان" },
                    new IntamediaCity() { Code = "134", Name = "آرمرده" },
                    new IntamediaCity() { Code = "135", Name = "بانه" },
                    new IntamediaCity() { Code = "136", Name = "کانی سور" },
                    new IntamediaCity() { Code = "137", Name = "بوئین سفلی" },
                    new IntamediaCity() { Code = "138", Name = "بابارشانی" },
                    new IntamediaCity() { Code = "139", Name = "یاسوکند" },
                    new IntamediaCity() { Code = "140", Name = "بیجار" },
                    new IntamediaCity() { Code = "141", Name = "صاحب" },
                    new IntamediaCity() { Code = "142", Name = "سقز" },
                    new IntamediaCity() { Code = "143", Name = "سنندج" },
                    new IntamediaCity() { Code = "144", Name = "شویشه" },
                    new IntamediaCity() { Code = "145", Name = "دهگلان" },
                    new IntamediaCity() { Code = "146", Name = "قروه" },
                    new IntamediaCity() { Code = "147", Name = "دلبران" },
                    new IntamediaCity() { Code = "148", Name = "سریش آباد" },
                    new IntamediaCity() { Code = "149", Name = "دزج" },
                    new IntamediaCity() { Code = "150", Name = "چناره" },
                    new IntamediaCity() { Code = "151", Name = "مریوان" },
                    new IntamediaCity() { Code = "152", Name = "زرینه" },
                    new IntamediaCity() { Code = "153", Name = "دیواندره" },
                    new IntamediaCity() { Code = "154", Name = "کامیاران" },
                    new IntamediaCity() { Code = "155", Name = "موچش" },
                    new IntamediaCity() { Code = "156", Name = "سروآباد" },
                    new IntamediaCity() { Code = "157", Name = "اردبیل" },
                    new IntamediaCity() { Code = "158", Name = "سرعین" },
                    new IntamediaCity() { Code = "159", Name = "هیر" },
                    new IntamediaCity() { Code = "160", Name = "بیله سوار" },
                    new IntamediaCity() { Code = "161", Name = "جعفراباد" },
                    new IntamediaCity() { Code = "162", Name = "اصلاندوز" },
                    new IntamediaCity() { Code = "163", Name = "پارس آباد" },
                    new IntamediaCity() { Code = "164", Name = "خلخال" },
                    new IntamediaCity() { Code = "165", Name = "کلور" },
                    new IntamediaCity() { Code = "166", Name = "هشتجین" },
                    new IntamediaCity() { Code = "167", Name = "گیوی" },
                    new IntamediaCity() { Code = "168", Name = "تازه کندانگوت" },
                    new IntamediaCity() { Code = "169", Name = "گرمی" },
                    new IntamediaCity() { Code = "170", Name = "رضی" },
                    new IntamediaCity() { Code = "171", Name = "لاهرود" },
                    new IntamediaCity() { Code = "172", Name = "مشگین شهر" },
                    new IntamediaCity() { Code = "173", Name = "آبی بیگلو" },
                    new IntamediaCity() { Code = "174", Name = "عنبران" },
                    new IntamediaCity() { Code = "175", Name = "نمین" },
                    new IntamediaCity() { Code = "176", Name = "کورائیم" },
                    new IntamediaCity() { Code = "177", Name = "نیر" },
                    new IntamediaCity() { Code = "178", Name = "ابرکوه" },
                    new IntamediaCity() { Code = "179", Name = "مهردشت" },
                    new IntamediaCity() { Code = "180", Name = "احمد آباد" },
                    new IntamediaCity() { Code = "181", Name = "اردکان" },
                    new IntamediaCity() { Code = "182", Name = "عقدا" },
                    new IntamediaCity() { Code = "183", Name = "بافق" },
                    new IntamediaCity() { Code = "184", Name = "بهاباد" },
                    new IntamediaCity() { Code = "185", Name = "تفت" },
                    new IntamediaCity() { Code = "186", Name = "نیر" },
                    new IntamediaCity() { Code = "187", Name = "مروست" },
                    new IntamediaCity() { Code = "188", Name = "هرات" },
                    new IntamediaCity() { Code = "189", Name = "اشکذر" },
                    new IntamediaCity() { Code = "190", Name = "خضر آباد" },
                    new IntamediaCity() { Code = "191", Name = "ندوشن" },
                    new IntamediaCity() { Code = "192", Name = "دیهوک" },
                    new IntamediaCity() { Code = "193", Name = "طبس" },
                    new IntamediaCity() { Code = "194", Name = "عشق آباد" },
                    new IntamediaCity() { Code = "195", Name = "مهریز" },
                    new IntamediaCity() { Code = "196", Name = "میبد" },
                    new IntamediaCity() { Code = "197", Name = "حمیدیا" },
                    new IntamediaCity() { Code = "198", Name = "زارچ" },
                    new IntamediaCity() { Code = "199", Name = "شاهدیه" },
                    new IntamediaCity() { Code = "200", Name = "یزد" },
                    new IntamediaCity() { Code = "201", Name = "بیرجند" },
                    new IntamediaCity() { Code = "202", Name = "خوسف" },
                    new IntamediaCity() { Code = "203", Name = "اسدیه" },
                    new IntamediaCity() { Code = "204", Name = "آیسک" },
                    new IntamediaCity() { Code = "205", Name = "سرایان" },
                    new IntamediaCity() { Code = "206", Name = "سه قلعه" },
                    new IntamediaCity() { Code = "207", Name = "سربیشه" },
                    new IntamediaCity() { Code = "208", Name = "مود" },
                    new IntamediaCity() { Code = "209", Name = "اسلامیه" },
                    new IntamediaCity() { Code = "210", Name = "بشرویه" },
                    new IntamediaCity() { Code = "211", Name = "فردوس" },
                    new IntamediaCity() { Code = "212", Name = "آرین شهر" },
                    new IntamediaCity() { Code = "213", Name = "اسفدن" },
                    new IntamediaCity() { Code = "214", Name = "حاجی آباد" },
                    new IntamediaCity() { Code = "215", Name = "خضری دشت بیاض" },
                    new IntamediaCity() { Code = "216", Name = "زهان" },
                    new IntamediaCity() { Code = "217", Name = "قاین" },
                    new IntamediaCity() { Code = "218", Name = "نیمبلوک" },
                    new IntamediaCity() { Code = "219", Name = "شوسف" },
                    new IntamediaCity() { Code = "220", Name = "نهبندان" },
                    new IntamediaCity() { Code = "221", Name = "ایرانشهر" },
                    new IntamediaCity() { Code = "222", Name = "بزمان" },
                    new IntamediaCity() { Code = "223", Name = "بمپور" },
                    new IntamediaCity() { Code = "224", Name = "گلمورتی" },
                    new IntamediaCity() { Code = "225", Name = "چابهار" },
                    new IntamediaCity() { Code = "226", Name = "نگور" },
                    new IntamediaCity() { Code = "227", Name = "خاش" },
                    new IntamediaCity() { Code = "228", Name = "نوک اباد" },
                    new IntamediaCity() { Code = "229", Name = "ادیمی" },
                    new IntamediaCity() { Code = "230", Name = "بنجار" },
                    new IntamediaCity() { Code = "231", Name = "دوست محمد" },
                    new IntamediaCity() { Code = "232", Name = "زابل" },
                    new IntamediaCity() { Code = "233", Name = "محمد آباد" },
                    new IntamediaCity() { Code = "234", Name = "زاهدان" },
                    new IntamediaCity() { Code = "235", Name = "میرجاوه" },
                    new IntamediaCity() { Code = "236", Name = "نصرت آباد" },
                    new IntamediaCity() { Code = "237", Name = "زهک" },
                    new IntamediaCity() { Code = "238", Name = "جالق" },
                    new IntamediaCity() { Code = "239", Name = "مهرستان" },
                    new IntamediaCity() { Code = "240", Name = "سراوان" },
                    new IntamediaCity() { Code = "241", Name = "سیرکان" },
                    new IntamediaCity() { Code = "242", Name = "هیدوچ" },
                    new IntamediaCity() { Code = "243", Name = "پیشین" },
                    new IntamediaCity() { Code = "244", Name = "راسک" },
                    new IntamediaCity() { Code = "245", Name = "سرباز" },
                    new IntamediaCity() { Code = "246", Name = "کنارک" },
                    new IntamediaCity() { Code = "247", Name = "اسپکه" },
                    new IntamediaCity() { Code = "248", Name = "بنت" },
                    new IntamediaCity() { Code = "249", Name = "فنوج" },
                    new IntamediaCity() { Code = "250", Name = "قصرقند" },
                    new IntamediaCity() { Code = "251", Name = "نیکشهر" },
                    new IntamediaCity() { Code = "252", Name = "اسکو" },
                    new IntamediaCity() { Code = "253", Name = "ایلخچی" },
                    new IntamediaCity() { Code = "254", Name = "اهر" },
                    new IntamediaCity() { Code = "255", Name = "هوراند" },
                    new IntamediaCity() { Code = "256", Name = "ابوموسی" },
                    new IntamediaCity() { Code = "257", Name = "بستک" },
                    new IntamediaCity() { Code = "258", Name = "جناح" },
                    new IntamediaCity() { Code = "259", Name = "بندرعباس" },
                    new IntamediaCity() { Code = "260", Name = "فین" },
                    new IntamediaCity() { Code = "261", Name = "چارک" },
                    new IntamediaCity() { Code = "262", Name = "بندرلنگه" },
                    new IntamediaCity() { Code = "263", Name = "کنگ" },
                    new IntamediaCity() { Code = "264", Name = "کیش" },
                    new IntamediaCity() { Code = "265", Name = "بندرجاسک" },
                    new IntamediaCity() { Code = "266", Name = "حاجی آباد" },
                    new IntamediaCity() { Code = "267", Name = "فارغان" },
                    new IntamediaCity() { Code = "268", Name = "خمیر" },
                    new IntamediaCity() { Code = "269", Name = "دهبارز" },
                    new IntamediaCity() { Code = "270", Name = "زیارت علی" },
                    new IntamediaCity() { Code = "271", Name = "درگهان" },
                    new IntamediaCity() { Code = "272", Name = "سوزا" },
                    new IntamediaCity() { Code = "273", Name = "قشم" },
                    new IntamediaCity() { Code = "274", Name = "هرمز" },
                    new IntamediaCity() { Code = "276", Name = "سیریک" },
                    new IntamediaCity() { Code = "277", Name = "میناب" },
                    new IntamediaCity() { Code = "278", Name = "اسلام شهر" },
                    new IntamediaCity() { Code = "279", Name = "چهاردانگه" },
                    new IntamediaCity() { Code = "280", Name = "پاکدشت" },
                    new IntamediaCity() { Code = "281", Name = "شریف آباد" },
                    new IntamediaCity() { Code = "282", Name = "بومهن" },
                    new IntamediaCity() { Code = "283", Name = "پردیس" },
                    new IntamediaCity() { Code = "284", Name = "تهران" },
                    new IntamediaCity() { Code = "285", Name = "آبسرد" },
                    new IntamediaCity() { Code = "286", Name = "آبعلی" },
                    new IntamediaCity() { Code = "287", Name = "دماوند" },
                    new IntamediaCity() { Code = "288", Name = "رودهن" },
                    new IntamediaCity() { Code = "289", Name = "کیلان" },
                    new IntamediaCity() { Code = "290", Name = "باقر شهر" },
                    new IntamediaCity() { Code = "291", Name = "حسن آباد" },
                    new IntamediaCity() { Code = "292", Name = "کهریزک" },
                    new IntamediaCity() { Code = "293", Name = "رباطکریم" },
                    new IntamediaCity() { Code = "294", Name = "صالح آباد" },
                    new IntamediaCity() { Code = "295", Name = "گلستان" },
                    new IntamediaCity() { Code = "296", Name = "نسیم شهر" },
                    new IntamediaCity() { Code = "297", Name = "نصیرآباد" },
                    new IntamediaCity() { Code = "298", Name = "چهارباغ" },
                    new IntamediaCity() { Code = "299", Name = "شهرجدیدهشتگرد" },
                    new IntamediaCity() { Code = "300", Name = "طالقان" },
                    new IntamediaCity() { Code = "301", Name = "کوهسار" },
                    new IntamediaCity() { Code = "302", Name = "هشتگرد" },
                    new IntamediaCity() { Code = "303", Name = "فشم" },
                    new IntamediaCity() { Code = "304", Name = "لواسان" },
                    new IntamediaCity() { Code = "305", Name = "اندیشه" },
                    new IntamediaCity() { Code = "306", Name = "باغستان" },
                    new IntamediaCity() { Code = "307", Name = "شاهدشهر" },
                    new IntamediaCity() { Code = "308", Name = "شهریار" },
                    new IntamediaCity() { Code = "309", Name = "رازمره" },
                    new IntamediaCity() { Code = "310", Name = "صفادشت" },
                    new IntamediaCity() { Code = "311", Name = "فردوسیه" },
                    new IntamediaCity() { Code = "312", Name = "قدس" },
                    new IntamediaCity() { Code = "313", Name = "ملارد" },
                    new IntamediaCity() { Code = "314", Name = "وحیدیه" },
                    new IntamediaCity() { Code = "315", Name = "ارجمند" },
                    new IntamediaCity() { Code = "316", Name = "فیروزکوه" },
                    new IntamediaCity() { Code = "317", Name = "اشتهارد" },
                    new IntamediaCity() { Code = "318", Name = "کرج" },
                    new IntamediaCity() { Code = "319", Name = "کمالشهر" },
                    new IntamediaCity() { Code = "320", Name = "گرمدره" },
                    new IntamediaCity() { Code = "321", Name = "ماهدشت" },
                    new IntamediaCity() { Code = "322", Name = "محمدشهر" },
                    new IntamediaCity() { Code = "323", Name = "مشکین دشت" },
                    new IntamediaCity() { Code = "324", Name = "نظرآباد" },
                    new IntamediaCity() { Code = "325", Name = "پیشوا" },
                    new IntamediaCity() { Code = "326", Name = "جواد آباد" },
                    new IntamediaCity() { Code = "327", Name = "قرچک" },
                    new IntamediaCity() { Code = "328", Name = "ورامین" },
                    new IntamediaCity() { Code = "329", Name = "امیدیه" },
                    new IntamediaCity() { Code = "330", Name = "جایزان" },
                    new IntamediaCity() { Code = "331", Name = "اندیمشک" },
                    new IntamediaCity() { Code = "332", Name = "حسینیه" },
                    new IntamediaCity() { Code = "333", Name = "اهواز" },
                    new IntamediaCity() { Code = "334", Name = "حمیدیه" },
                    new IntamediaCity() { Code = "335", Name = "شیبان" },
                    new IntamediaCity() { Code = "336", Name = "ملاثانی" },
                    new IntamediaCity() { Code = "337", Name = "ویس" },
                    new IntamediaCity() { Code = "338", Name = "ایذه" },
                    new IntamediaCity() { Code = "339", Name = "دهدز" },
                    new IntamediaCity() { Code = "340", Name = "اروندکنار" },
                    new IntamediaCity() { Code = "341", Name = "آبادان" },
                    new IntamediaCity() { Code = "342", Name = "باغ ملک" },
                    new IntamediaCity() { Code = "343", Name = "صیدون" },
                    new IntamediaCity() { Code = "344", Name = "قلعه تل" },
                    new IntamediaCity() { Code = "345", Name = "بندرامام خمینی" },
                    new IntamediaCity() { Code = "346", Name = "بندرماهشهر" },
                    new IntamediaCity() { Code = "347", Name = "چمران" },
                    new IntamediaCity() { Code = "348", Name = "آغاجاری" },
                    new IntamediaCity() { Code = "349", Name = "بهبهان" },
                    new IntamediaCity() { Code = "350", Name = "سردشت" },
                    new IntamediaCity() { Code = "351", Name = "خرمشهر" },
                    new IntamediaCity() { Code = "352", Name = "مینوشهر" },
                    new IntamediaCity() { Code = "353", Name = "امام" },
                    new IntamediaCity() { Code = "354", Name = "دزفول" },
                    new IntamediaCity() { Code = "355", Name = "سالند" },
                    new IntamediaCity() { Code = "356", Name = "صفی آباد" },
                    new IntamediaCity() { Code = "357", Name = "میانرود" },
                    new IntamediaCity() { Code = "358", Name = "بستان" },
                    new IntamediaCity() { Code = "359", Name = "رفیع" },
                    new IntamediaCity() { Code = "360", Name = "سوسنگرد" },
                    new IntamediaCity() { Code = "361", Name = "هویزه" },
                    new IntamediaCity() { Code = "362", Name = "رامشیر" },
                    new IntamediaCity() { Code = "363", Name = "رامهرمز" },
                    new IntamediaCity() { Code = "364", Name = "هفتگل" },
                    new IntamediaCity() { Code = "365", Name = "شادگان" },
                    new IntamediaCity() { Code = "366", Name = "الوان" },
                    new IntamediaCity() { Code = "367", Name = "شاوور" },
                    new IntamediaCity() { Code = "368", Name = "شوش" },
                    new IntamediaCity() { Code = "369", Name = "شوشتر" },
                    new IntamediaCity() { Code = "370", Name = "گتوند" },
                    new IntamediaCity() { Code = "371", Name = "لالی" },
                    new IntamediaCity() { Code = "372", Name = "قلعه خواجه" },
                    new IntamediaCity() { Code = "373", Name = "مسجدسلیمان" },
                    new IntamediaCity() { Code = "374", Name = "زهره" },
                    new IntamediaCity() { Code = "375", Name = "هندیجان" },
                    new IntamediaCity() { Code = "376", Name = "آباده" },
                    new IntamediaCity() { Code = "377", Name = "ایزدخواست" },
                    new IntamediaCity() { Code = "378", Name = "بهمن" },
                    new IntamediaCity() { Code = "379", Name = "سورمق" },
                    new IntamediaCity() { Code = "381", Name = "ارسنجان" },
                    new IntamediaCity() { Code = "382", Name = "استهبان" },
                    new IntamediaCity() { Code = "383", Name = "ایج" },
                    new IntamediaCity() { Code = "384", Name = "رونیز" },
                    new IntamediaCity() { Code = "385", Name = "اقلید" },
                    new IntamediaCity() { Code = "386", Name = "سده" },
                    new IntamediaCity() { Code = "387", Name = "بوانات" },
                    new IntamediaCity() { Code = "389", Name = "سعادت شهر" },
                    new IntamediaCity() { Code = "390", Name = "باب انار" },
                    new IntamediaCity() { Code = "391", Name = "جهرم" },
                    new IntamediaCity() { Code = "392", Name = "خاوران" },
                    new IntamediaCity() { Code = "393", Name = "قطب آباد" },
                    new IntamediaCity() { Code = "394", Name = "صفاشهر" },
                    new IntamediaCity() { Code = "395", Name = "قادرآباد" },
                    new IntamediaCity() { Code = "396", Name = "خنج" },
                    new IntamediaCity() { Code = "397", Name = "جنت شهر" },
                    new IntamediaCity() { Code = "398", Name = "داراب" },
                    new IntamediaCity() { Code = "399", Name = "حاجی آباد" },
                    new IntamediaCity() { Code = "402", Name = "اردکان" },
                    new IntamediaCity() { Code = "403", Name = "بیضا" },
                    new IntamediaCity() { Code = "404", Name = "خرامه" },
                    new IntamediaCity() { Code = "405", Name = "داریان" },
                    new IntamediaCity() { Code = "406", Name = "زرقان" },
                    new IntamediaCity() { Code = "407", Name = "سروستان" },
                    new IntamediaCity() { Code = "408", Name = "شیراز" },
                    new IntamediaCity() { Code = "409", Name = "کوار" },
                    new IntamediaCity() { Code = "410", Name = "لپوئی" },
                    new IntamediaCity() { Code = "411", Name = "فراشبند" },
                    new IntamediaCity() { Code = "412", Name = "زاهدشهر" },
                    new IntamediaCity() { Code = "413", Name = "ششده" },
                    new IntamediaCity() { Code = "414", Name = "فسا" },
                    new IntamediaCity() { Code = "415", Name = "نوبندگان" },
                    new IntamediaCity() { Code = "416", Name = "فیروز آباد" },
                    new IntamediaCity() { Code = "417", Name = "میمند" },
                    new IntamediaCity() { Code = "418", Name = "افزر" },
                    new IntamediaCity() { Code = "419", Name = "کارزین" },
                    new IntamediaCity() { Code = "421", Name = "بالاده" },
                    new IntamediaCity() { Code = "422", Name = "خشت" },
                    new IntamediaCity() { Code = "423", Name = "قائمیه" },
                    new IntamediaCity() { Code = "424", Name = "کازرون" },
                    new IntamediaCity() { Code = "425", Name = "کنار تخته" },
                    new IntamediaCity() { Code = "426", Name = "نودان" },
                    new IntamediaCity() { Code = "427", Name = "اوز" },
                    new IntamediaCity() { Code = "428", Name = "بنارویه" },
                    new IntamediaCity() { Code = "429", Name = "بیرم" },
                    new IntamediaCity() { Code = "430", Name = "جویم" },
                    new IntamediaCity() { Code = "431", Name = "خور" },
                    new IntamediaCity() { Code = "432", Name = "گراش" },
                    new IntamediaCity() { Code = "433", Name = "لار" },
                    new IntamediaCity() { Code = "434", Name = "اشکنان" },
                    new IntamediaCity() { Code = "435", Name = "اهل" },
                    new IntamediaCity() { Code = "436", Name = "علامرودشت" },
                    new IntamediaCity() { Code = "437", Name = "لامرد" },
                    new IntamediaCity() { Code = "438", Name = "سیدان" },
                    new IntamediaCity() { Code = "439", Name = "کامفیروز" },
                    new IntamediaCity() { Code = "440", Name = "مرودشت" },
                    new IntamediaCity() { Code = "441", Name = "مصیری" },
                    new IntamediaCity() { Code = "442", Name = "نورآباد" },
                    new IntamediaCity() { Code = "444", Name = "مهر" },
                    new IntamediaCity() { Code = "445", Name = "وراوی" },
                    new IntamediaCity() { Code = "446", Name = "آباده طشک" },
                    new IntamediaCity() { Code = "447", Name = "مشکان" },
                    new IntamediaCity() { Code = "448", Name = "نی ریز" },
                    new IntamediaCity() { Code = "449", Name = "ارزوئیه" },
                    new IntamediaCity() { Code = "450", Name = "بافت" },
                    new IntamediaCity() { Code = "451", Name = "بزنجان" },
                    new IntamediaCity() { Code = "452", Name = "رابر" },
                    new IntamediaCity() { Code = "453", Name = "بردسیر" },
                    new IntamediaCity() { Code = "454", Name = "گلزار" },
                    new IntamediaCity() { Code = "455", Name = "نگار" },
                    new IntamediaCity() { Code = "456", Name = "بروات" },
                    new IntamediaCity() { Code = "457", Name = "بم" },
                    new IntamediaCity() { Code = "458", Name = "فهرج" },
                    new IntamediaCity() { Code = "459", Name = "محمد آباد" },
                    new IntamediaCity() { Code = "460", Name = "نرماشیر" },
                    new IntamediaCity() { Code = "461", Name = "نظام شهر" },
                    new IntamediaCity() { Code = "462", Name = "جبالبارز" },
                    new IntamediaCity() { Code = "463", Name = "جیرفت" },
                    new IntamediaCity() { Code = "464", Name = "درب بهشت" },
                    new IntamediaCity() { Code = "465", Name = "راور" },
                    new IntamediaCity() { Code = "466", Name = "هجدک" },
                    new IntamediaCity() { Code = "467", Name = "انار" },
                    new IntamediaCity() { Code = "468", Name = "بهرمان" },
                    new IntamediaCity() { Code = "469", Name = "حسین ابادجدید" },
                    new IntamediaCity() { Code = "470", Name = "رفسنجان" },
                    new IntamediaCity() { Code = "471", Name = "کشکوئیه" },
                    new IntamediaCity() { Code = "472", Name = "سرچشمه" },
                    new IntamediaCity() { Code = "473", Name = "رودبار" },
                    new IntamediaCity() { Code = "474", Name = "خانوک" },
                    new IntamediaCity() { Code = "475", Name = "ریحان" },
                    new IntamediaCity() { Code = "476", Name = "زرند" },
                    new IntamediaCity() { Code = "477", Name = "یزدان شهر" },
                    new IntamediaCity() { Code = "478", Name = "پاریز" },
                    new IntamediaCity() { Code = "479", Name = "زیدآباد" },
                    new IntamediaCity() { Code = "480", Name = "سیرجان" },
                    new IntamediaCity() { Code = "481", Name = "نجف شهر" },
                    new IntamediaCity() { Code = "482", Name = "دهج" },
                    new IntamediaCity() { Code = "483", Name = "شهربابک" },
                    new IntamediaCity() { Code = "484", Name = "عنبرآباد" },
                    new IntamediaCity() { Code = "485", Name = "مردهک" },
                    new IntamediaCity() { Code = "486", Name = "قلعه گنج" },
                    new IntamediaCity() { Code = "487", Name = "اختیارآباد" },
                    new IntamediaCity() { Code = "488", Name = "اندوهجرد" },
                    new IntamediaCity() { Code = "489", Name = "باغین" },
                    new IntamediaCity() { Code = "490", Name = "جوپار" },
                    new IntamediaCity() { Code = "491", Name = "راین" },
                    new IntamediaCity() { Code = "492", Name = "زنگی آباد" },
                    new IntamediaCity() { Code = "493", Name = "شهداد" },
                    new IntamediaCity() { Code = "494", Name = "کاظم آباد" },
                    new IntamediaCity() { Code = "495", Name = "کرمان" },
                    new IntamediaCity() { Code = "496", Name = "گلباف" },
                    new IntamediaCity() { Code = "497", Name = "ماهان" },
                    new IntamediaCity() { Code = "498", Name = "محی آباد" },
                    new IntamediaCity() { Code = "499", Name = "چترود" },
                    new IntamediaCity() { Code = "500", Name = "کوهبنان" },
                    new IntamediaCity() { Code = "501", Name = "کیانشهر" },
                    new IntamediaCity() { Code = "502", Name = "فاریاب" },
                    new IntamediaCity() { Code = "503", Name = "کهنوج" },
                    new IntamediaCity() { Code = "504", Name = "منوجان" },
                    new IntamediaCity() { Code = "505", Name = "نودژ" },
                    new IntamediaCity() { Code = "506", Name = "انابد" },
                    new IntamediaCity() { Code = "507", Name = "بردسکن" },
                    new IntamediaCity() { Code = "508", Name = "باخرز" },
                    new IntamediaCity() { Code = "509", Name = "تایباد" },
                    new IntamediaCity() { Code = "510", Name = "کاریز" },
                    new IntamediaCity() { Code = "511", Name = "مشهدریزه" },
                    new IntamediaCity() { Code = "512", Name = "تربت جام" },
                    new IntamediaCity() { Code = "513", Name = "صالح آباد" },
                    new IntamediaCity() { Code = "514", Name = "نصرآباد" },
                    new IntamediaCity() { Code = "515", Name = "نیل شهر" },
                    new IntamediaCity() { Code = "516", Name = "بایک" },
                    new IntamediaCity() { Code = "517", Name = "تربت حیدریه" },
                    new IntamediaCity() { Code = "518", Name = "دولت آباد" },
                    new IntamediaCity() { Code = "519", Name = "رباط سنگ" },
                    new IntamediaCity() { Code = "520", Name = "کدکن" },
                    new IntamediaCity() { Code = "521", Name = "چناران" },
                    new IntamediaCity() { Code = "522", Name = "خلیل آباد" },
                    new IntamediaCity() { Code = "523", Name = "کندر" },
                    new IntamediaCity() { Code = "524", Name = "خواف" },
                    new IntamediaCity() { Code = "525", Name = "سلامی" },
                    new IntamediaCity() { Code = "526", Name = "سنگان" },
                    new IntamediaCity() { Code = "527", Name = "قاسم آباد" },
                    new IntamediaCity() { Code = "528", Name = "نشتیفان" },
                    new IntamediaCity() { Code = "529", Name = "چاپشلو" },
                    new IntamediaCity() { Code = "530", Name = "درگز" },
                    new IntamediaCity() { Code = "531", Name = "لطف آباد" },
                    new IntamediaCity() { Code = "532", Name = "نوخندان" },
                    new IntamediaCity() { Code = "533", Name = "جنگل" },
                    new IntamediaCity() { Code = "534", Name = "رشتخوار" },
                    new IntamediaCity() { Code = "535", Name = "جغتای" },
                    new IntamediaCity() { Code = "536", Name = "داورزن" },
                    new IntamediaCity() { Code = "537", Name = "روداب" },
                    new IntamediaCity() { Code = "538", Name = "سبزوار" },
                    new IntamediaCity() { Code = "539", Name = "سلطان آباد" },
                    new IntamediaCity() { Code = "540", Name = "ششتمد" },
                    new IntamediaCity() { Code = "541", Name = "نقاب" },
                    new IntamediaCity() { Code = "542", Name = "سرخس" },
                    new IntamediaCity() { Code = "543", Name = "مزدآوند" },
                    new IntamediaCity() { Code = "544", Name = "سفید سنگ" },
                    new IntamediaCity() { Code = "545", Name = "فرهادگرد" },
                    new IntamediaCity() { Code = "546", Name = "فریمان" },
                    new IntamediaCity() { Code = "547", Name = "قلندر آباد" },
                    new IntamediaCity() { Code = "548", Name = "باجگیران" },
                    new IntamediaCity() { Code = "549", Name = "قوچان" },
                    new IntamediaCity() { Code = "550", Name = "ریوش" },
                    new IntamediaCity() { Code = "551", Name = "کاشمر" },
                    new IntamediaCity() { Code = "552", Name = "شهرزو" },
                    new IntamediaCity() { Code = "553", Name = "کلات" },
                    new IntamediaCity() { Code = "554", Name = "بجستان" },
                    new IntamediaCity() { Code = "555", Name = "بیدخت" },
                    new IntamediaCity() { Code = "556", Name = "کاخک" },
                    new IntamediaCity() { Code = "557", Name = "گناباد" },
                    new IntamediaCity() { Code = "558", Name = "یونسی" },
                    new IntamediaCity() { Code = "559", Name = "رضویه" },
                    new IntamediaCity() { Code = "560", Name = "شاندیز" },
                    new IntamediaCity() { Code = "561", Name = "طرقبه" },
                    new IntamediaCity() { Code = "562", Name = "مشهد" },
                    new IntamediaCity() { Code = "563", Name = "ملک آباد" },
                    new IntamediaCity() { Code = "564", Name = "فیض آباد" },
                    new IntamediaCity() { Code = "565", Name = "چکنه" },
                    new IntamediaCity() { Code = "566", Name = "خرو" },
                    new IntamediaCity() { Code = "567", Name = "خشکرود" },
                    new IntamediaCity() { Code = "568", Name = "عشق آباد" },
                    new IntamediaCity() { Code = "569", Name = "فیروزه" },
                    new IntamediaCity() { Code = "570", Name = "قدمگاه" },
                    new IntamediaCity() { Code = "571", Name = "نیشابور" },
                    new IntamediaCity() { Code = "572", Name = "اسفراین" },
                    new IntamediaCity() { Code = "573", Name = "صفی آباد" },
                    new IntamediaCity() { Code = "574", Name = "بجنورد" },
                    new IntamediaCity() { Code = "575", Name = "حصار گرمخان" },
                    new IntamediaCity() { Code = "576", Name = "راز" },
                    new IntamediaCity() { Code = "577", Name = "درق" },
                    new IntamediaCity() { Code = "578", Name = "سنخواست" },
                    new IntamediaCity() { Code = "579", Name = "شوقان" },
                    new IntamediaCity() { Code = "580", Name = "جاجرم" },
                    new IntamediaCity() { Code = "581", Name = "شیروان" },
                    new IntamediaCity() { Code = "582", Name = "لوجلی" },
                    new IntamediaCity() { Code = "583", Name = "فاروج" },
                    new IntamediaCity() { Code = "584", Name = "آشخانه" },
                    new IntamediaCity() { Code = "585", Name = "پیش قلعه" },
                    new IntamediaCity() { Code = "586", Name = "قاضی" },
                    new IntamediaCity() { Code = "587", Name = "آزاد شهر" },
                    new IntamediaCity() { Code = "588", Name = "نوده خاندوز" },
                    new IntamediaCity() { Code = "589", Name = "نگین شهر" },
                    new IntamediaCity() { Code = "590", Name = "انبار آلوم" },
                    new IntamediaCity() { Code = "591", Name = "آق قلا" },
                    new IntamediaCity() { Code = "592", Name = "بندر گز" },
                    new IntamediaCity() { Code = "593", Name = "نوکنده" },
                    new IntamediaCity() { Code = "594", Name = "بندرترکمن" },
                    new IntamediaCity() { Code = "595", Name = "سیمین شهر" },
                    new IntamediaCity() { Code = "596", Name = "گمیش تپه" },
                    new IntamediaCity() { Code = "597", Name = "خان ببین" },
                    new IntamediaCity() { Code = "598", Name = "دلند" },
                    new IntamediaCity() { Code = "599", Name = "رامیان" },
                    new IntamediaCity() { Code = "600", Name = "علی آباد" },
                    new IntamediaCity() { Code = "601", Name = "فاضل آباد" },
                    new IntamediaCity() { Code = "602", Name = "کردکوی" },
                    new IntamediaCity() { Code = "603", Name = "کلاله" },
                    new IntamediaCity() { Code = "604", Name = "مراوه تپه" },
                    new IntamediaCity() { Code = "605", Name = "سرخنکلاته" },
                    new IntamediaCity() { Code = "607", Name = "گرگان" },
                    new IntamediaCity() { Code = "608", Name = "اینچه برون" },
                    new IntamediaCity() { Code = "609", Name = "گنبد کاووس" },
                    new IntamediaCity() { Code = "610", Name = "گالیکش" },
                    new IntamediaCity() { Code = "611", Name = "مینو دشت" },
                    new IntamediaCity() { Code = "612", Name = "آبیک" },
                    new IntamediaCity() { Code = "613", Name = "خاکعلی" },
                    new IntamediaCity() { Code = "614", Name = "الوند" },
                    new IntamediaCity() { Code = "615", Name = "بیدستان" },
                    new IntamediaCity() { Code = "616", Name = "محمدیه" },
                    new IntamediaCity() { Code = "617", Name = "آوج" },
                    new IntamediaCity() { Code = "618", Name = "آبگرم" },
                    new IntamediaCity() { Code = "619", Name = "ارداق" },
                    new IntamediaCity() { Code = "620", Name = "بوئین زهرا" },
                    new IntamediaCity() { Code = "621", Name = "دانسفهان" },
                    new IntamediaCity() { Code = "622", Name = "سگز آباد" },
                    new IntamediaCity() { Code = "623", Name = "شال" },
                    new IntamediaCity() { Code = "624", Name = "اسفرورین" },
                    new IntamediaCity() { Code = "625", Name = "تاکستان" },
                    new IntamediaCity() { Code = "626", Name = "شهرصنعتی خرمدشت" },
                    new IntamediaCity() { Code = "627", Name = "ضیاءآباد" },
                    new IntamediaCity() { Code = "628", Name = "نرجه" },
                    new IntamediaCity() { Code = "629", Name = "اقبالیه" },
                    new IntamediaCity() { Code = "630", Name = "رازمیان" },
                    new IntamediaCity() { Code = "631", Name = "سیردان" },
                    new IntamediaCity() { Code = "632", Name = "قزوین" },
                    new IntamediaCity() { Code = "633", Name = "کوهین" },
                    new IntamediaCity() { Code = "634", Name = "معلم کلایه" },
                    new IntamediaCity() { Code = "635", Name = "محمودآبادنمونه" },
                    new IntamediaCity() { Code = "636", Name = "جعفریه (قلعه جعفربیک )" },
                    new IntamediaCity() { Code = "637", Name = "دستجرد" },
                    new IntamediaCity() { Code = "638", Name = "قم" },
                    new IntamediaCity() { Code = "639", Name = "قنوات" },
                    new IntamediaCity() { Code = "640", Name = "کهک" },
                    new IntamediaCity() { Code = "641", Name = "خنداب" },
                    new IntamediaCity() { Code = "642", Name = "اراک" },
                    new IntamediaCity() { Code = "643", Name = "سنجان" },
                    new IntamediaCity() { Code = "644", Name = "داوداباد" },
                    new IntamediaCity() { Code = "645", Name = "کرهرود" },
                    new IntamediaCity() { Code = "646", Name = "آشتیان" },
                    new IntamediaCity() { Code = "647", Name = "فرمهین" },
                    new IntamediaCity() { Code = "649", Name = "خمین" },
                    new IntamediaCity() { Code = "650", Name = "قورچی باشی" },
                    new IntamediaCity() { Code = "651", Name = "دلیجان" },
                    new IntamediaCity() { Code = "652", Name = "نراق" },
                    new IntamediaCity() { Code = "653", Name = "ساوه" },
                    new IntamediaCity() { Code = "654", Name = "غرق آباد" },
                    new IntamediaCity() { Code = "655", Name = "نوبران" },
                    new IntamediaCity() { Code = "656", Name = "آستانه" },
                    new IntamediaCity() { Code = "657", Name = "شازند" },
                    new IntamediaCity() { Code = "658", Name = "هندودر" },
                    new IntamediaCity() { Code = "659", Name = "توره" },
                    new IntamediaCity() { Code = "660", Name = "محلات" },
                    new IntamediaCity() { Code = "661", Name = "نیمور" },
                    new IntamediaCity() { Code = "662", Name = "رازقان" },
                    new IntamediaCity() { Code = "663", Name = "زاویه" },
                    new IntamediaCity() { Code = "664", Name = "مامونیه" },
                    new IntamediaCity() { Code = "665", Name = "پرندک" },
                    new IntamediaCity() { Code = "666", Name = "کمیجان" },
                    new IntamediaCity() { Code = "667", Name = "میلاجرد" },
                    new IntamediaCity() { Code = "668", Name = "رینه" },
                    new IntamediaCity() { Code = "669", Name = "گزنک" },
                    new IntamediaCity() { Code = "670", Name = "آمل" },
                    new IntamediaCity() { Code = "671", Name = "دابودشت" },
                    new IntamediaCity() { Code = "672", Name = "خوشرودپی" },
                    new IntamediaCity() { Code = "673", Name = "امیرکلا" },
                    new IntamediaCity() { Code = "674", Name = "بابل" },
                    new IntamediaCity() { Code = "675", Name = "گلوگاه" },
                    new IntamediaCity() { Code = "676", Name = "مرزی کلا" },
                    new IntamediaCity() { Code = "677", Name = "زرگرمحله" },
                    new IntamediaCity() { Code = "678", Name = "گتاب" },
                    new IntamediaCity() { Code = "679", Name = "بهشهر" },
                    new IntamediaCity() { Code = "680", Name = "رستم کلا" },
                    new IntamediaCity() { Code = "681", Name = "خلیل شهر" },
                    new IntamediaCity() { Code = "682", Name = "سلمانشهر" },
                    new IntamediaCity() { Code = "683", Name = "عباس آباد" },
                    new IntamediaCity() { Code = "685", Name = "تنکابن" },
                    new IntamediaCity() { Code = "686", Name = "نشتارود" },
                    new IntamediaCity() { Code = "687", Name = "خرم آباد" },
                    new IntamediaCity() { Code = "688", Name = "رامسر" },
                    new IntamediaCity() { Code = "689", Name = "سادات محله" },
                    new IntamediaCity() { Code = "690", Name = "کیاسر" },
                    new IntamediaCity() { Code = "691", Name = "فریم" },
                    new IntamediaCity() { Code = "692", Name = "ساری" },
                    new IntamediaCity() { Code = "693", Name = "سورک" },
                    new IntamediaCity() { Code = "694", Name = "شیرگاه" },
                    new IntamediaCity() { Code = "695", Name = "آلاشت" },
                    new IntamediaCity() { Code = "696", Name = "پل سفید" },
                    new IntamediaCity() { Code = "697", Name = "زیر آب" },
                    new IntamediaCity() { Code = "698", Name = "قائم شهر" },
                    new IntamediaCity() { Code = "699", Name = "کیاکلا" },
                    new IntamediaCity() { Code = "700", Name = "بلده" },
                    new IntamediaCity() { Code = "701", Name = "چمستان" },
                    new IntamediaCity() { Code = "702", Name = "نور" },
                    new IntamediaCity() { Code = "703", Name = "رویان" },
                    new IntamediaCity() { Code = "704", Name = "ایزدشهر" },
                    new IntamediaCity() { Code = "705", Name = "نوشهر" },
                    new IntamediaCity() { Code = "706", Name = "فریدون کنار" },
                    new IntamediaCity() { Code = "707", Name = "بابلسر" },
                    new IntamediaCity() { Code = "708", Name = "بهنمیر" },
                    new IntamediaCity() { Code = "709", Name = "کله بست" },
                    new IntamediaCity() { Code = "710", Name = "سرخرود" },
                    new IntamediaCity() { Code = "711", Name = "محمودآباد" },
                    new IntamediaCity() { Code = "712", Name = "نکا" },
                    new IntamediaCity() { Code = "713", Name = "کلاردشت" },
                    new IntamediaCity() { Code = "714", Name = "مرزن آباد" },
                    new IntamediaCity() { Code = "715", Name = "چالوس" },
                    new IntamediaCity() { Code = "716", Name = "کوهی خیل" },
                    new IntamediaCity() { Code = "717", Name = "جویبار" },
                    new IntamediaCity() { Code = "718", Name = "گلوگاه" },
                    new IntamediaCity() { Code = "719", Name = "آستارا" },
                    new IntamediaCity() { Code = "720", Name = "لوندویل" },
                    new IntamediaCity() { Code = "721", Name = "کیاشهر" },
                    new IntamediaCity() { Code = "722", Name = "آستانه اشرفیه" },
                    new IntamediaCity() { Code = "723", Name = "بندرانزلی" },
                    new IntamediaCity() { Code = "724", Name = "هشتپر" },
                    new IntamediaCity() { Code = "725", Name = "لیسار" },
                    new IntamediaCity() { Code = "726", Name = "اسالم" },
                    new IntamediaCity() { Code = "727", Name = "حویق" },
                    new IntamediaCity() { Code = "728", Name = "چوبر" },
                    new IntamediaCity() { Code = "729", Name = "خمام" },
                    new IntamediaCity() { Code = "730", Name = "سنگر" },
                    new IntamediaCity() { Code = "731", Name = "کوچصفهان" },
                    new IntamediaCity() { Code = "732", Name = "لشت نشاء" },
                    new IntamediaCity() { Code = "733", Name = "رشت" },
                    new IntamediaCity() { Code = "734", Name = "خشکبیجار" },
                    new IntamediaCity() { Code = "735", Name = "توتکابن" },
                    new IntamediaCity() { Code = "736", Name = "جیرنده" },
                    new IntamediaCity() { Code = "737", Name = "اوشان" },
                    new IntamediaCity() { Code = "738", Name = "رودبار" },
                    new IntamediaCity() { Code = "739", Name = "منجیل" },
                    new IntamediaCity() { Code = "740", Name = "رستم آباد" },
                    new IntamediaCity() { Code = "741", Name = "بره سر" },
                    new IntamediaCity() { Code = "742", Name = "رحیم آباد" },
                    new IntamediaCity() { Code = "743", Name = "رودسر" },
                    new IntamediaCity() { Code = "744", Name = "چابکسر" },
                    new IntamediaCity() { Code = "745", Name = "کلاچای" },
                    new IntamediaCity() { Code = "746", Name = "واجارگاه" },
                    new IntamediaCity() { Code = "747", Name = "مرجقل" },
                    new IntamediaCity() { Code = "748", Name = "صومعه سرا" },
                    new IntamediaCity() { Code = "749", Name = "گوراب زرمیخ" },
                    new IntamediaCity() { Code = "750", Name = "فومن" },
                    new IntamediaCity() { Code = "751", Name = "ماسوله" },
                    new IntamediaCity() { Code = "752", Name = "لنگرود" },
                    new IntamediaCity() { Code = "753", Name = "اطاقور" },
                    new IntamediaCity() { Code = "754", Name = "کومله" },
                    new IntamediaCity() { Code = "755", Name = "شلمان" },
                    new IntamediaCity() { Code = "756", Name = "لاهیجان" },
                    new IntamediaCity() { Code = "757", Name = "رودبنه" },
                    new IntamediaCity() { Code = "758", Name = "احمد سر گوراب" },
                    new IntamediaCity() { Code = "759", Name = "شفت" },
                    new IntamediaCity() { Code = "760", Name = "رانکوه" },
                    new IntamediaCity() { Code = "761", Name = "املش" },
                    new IntamediaCity() { Code = "762", Name = "پره سر" },
                    new IntamediaCity() { Code = "763", Name = "رضوانشهر" },
                    new IntamediaCity() { Code = "764", Name = "دیلمان" },
                    new IntamediaCity() { Code = "765", Name = "سیاهکل" },
                    new IntamediaCity() { Code = "766", Name = "بازار جمعه" },
                    new IntamediaCity() { Code = "767", Name = "ماسال" },
                    new IntamediaCity() { Code = "768", Name = "قوشچی" },
                    new IntamediaCity() { Code = "769", Name = "سیلوانه" },
                    new IntamediaCity() { Code = "770", Name = "سرو" },
                    new IntamediaCity() { Code = "771", Name = "ارومیه" },
                    new IntamediaCity() { Code = "772", Name = "نوشین" },
                    new IntamediaCity() { Code = "773", Name = "پیرانشهر" },
                    new IntamediaCity() { Code = "774", Name = "گردکشانه" },
                    new IntamediaCity() { Code = "776", Name = "خوی" },
                    new IntamediaCity() { Code = "777", Name = "فیرورق" },
                    new IntamediaCity() { Code = "778", Name = "ایواوغلی" },
                    new IntamediaCity() { Code = "779", Name = "سردشت" },
                    new IntamediaCity() { Code = "780", Name = "ربط" },
                    new IntamediaCity() { Code = "781", Name = "میرآباد" },
                    new IntamediaCity() { Code = "782", Name = "تازه شهر" },
                    new IntamediaCity() { Code = "783", Name = "سلماس" },
                    new IntamediaCity() { Code = "784", Name = "پلدشت" },
                    new IntamediaCity() { Code = "785", Name = "شوط" },
                    new IntamediaCity() { Code = "786", Name = "ماکو" },
                    new IntamediaCity() { Code = "787", Name = "بازرگان" },
                    new IntamediaCity() { Code = "788", Name = "مهاباد" },
                    new IntamediaCity() { Code = "789", Name = "میاندوآب" },
                    new IntamediaCity() { Code = "790", Name = "چهار برج" },
                    new IntamediaCity() { Code = "791", Name = "باروق" },
                    new IntamediaCity() { Code = "792", Name = "نقده" },
                    new IntamediaCity() { Code = "793", Name = "محمدیار" },
                    new IntamediaCity() { Code = "794", Name = "سیمینه" },
                    new IntamediaCity() { Code = "795", Name = "بوکان" },
                    new IntamediaCity() { Code = "796", Name = "شاهیندژ" },
                    new IntamediaCity() { Code = "797", Name = "محمودآباد" },
                    new IntamediaCity() { Code = "798", Name = "اقبال" },
                    new IntamediaCity() { Code = "799", Name = "تکاب" },
                    new IntamediaCity() { Code = "800", Name = "اشنویه" },
                    new IntamediaCity() { Code = "801", Name = "نالوس" },
                    new IntamediaCity() { Code = "802", Name = "آواجیق" },
                    new IntamediaCity() { Code = "803", Name = "سیه چشمه" },
                    new IntamediaCity() { Code = "804", Name = "حمیل" },
                    new IntamediaCity() { Code = "805", Name = "اسلام آبادغرب" },
                    new IntamediaCity() { Code = "806", Name = "هلشی" },
                    new IntamediaCity() { Code = "807", Name = "کرمانشاه" },
                    new IntamediaCity() { Code = "808", Name = "رباط" },
                    new IntamediaCity() { Code = "809", Name = "کوزران" },
                    new IntamediaCity() { Code = "810", Name = "باینگان" },
                    new IntamediaCity() { Code = "811", Name = "پاوه" },
                    new IntamediaCity() { Code = "812", Name = "نودشه" },
                    new IntamediaCity() { Code = "813", Name = "سرپل ذهاب" },
                    new IntamediaCity() { Code = "814", Name = "سنقر" },
                    new IntamediaCity() { Code = "815", Name = "سطر" },
                    new IntamediaCity() { Code = "816", Name = "سومار" },
                    new IntamediaCity() { Code = "817", Name = "قصرشیرین" },
                    new IntamediaCity() { Code = "818", Name = "کنگاور" },
                    new IntamediaCity() { Code = "819", Name = "گیلانغرب" },
                    new IntamediaCity() { Code = "820", Name = "سرمست" },
                    new IntamediaCity() { Code = "821", Name = "جوانرود" },
                    new IntamediaCity() { Code = "822", Name = "میانراهان" },
                    new IntamediaCity() { Code = "823", Name = "صحنه" },
                    new IntamediaCity() { Code = "824", Name = "بیستون" },
                    new IntamediaCity() { Code = "825", Name = "هرسین" },
                    new IntamediaCity() { Code = "826", Name = "تازه آباد" },
                    new IntamediaCity() { Code = "827", Name = "ازگله" },
                    new IntamediaCity() { Code = "828", Name = "گهواره" },
                    new IntamediaCity() { Code = "829", Name = "کرندغرب" },
                    new IntamediaCity() { Code = "830", Name = "روانسر" },
                    new IntamediaCity() { Code = "831", Name = "گراب سفلی" },
                    new IntamediaCity() { Code = "832", Name = "مارگون" },
                    new IntamediaCity() { Code = "833", Name = "یاسوج" },
                    new IntamediaCity() { Code = "834", Name = "لیکک" },
                    new IntamediaCity() { Code = "835", Name = "سی سخت" },
                    new IntamediaCity() { Code = "836", Name = "چرام" },
                    new IntamediaCity() { Code = "837", Name = "دهدشت" },
                    new IntamediaCity() { Code = "838", Name = "دیشموک" },
                    new IntamediaCity() { Code = "839", Name = "سوق" },
                    new IntamediaCity() { Code = "840", Name = "قلعه رییسی" },
                    new IntamediaCity() { Code = "841", Name = "لنده" },
                    new IntamediaCity() { Code = "842", Name = "باشت" },
                    new IntamediaCity() { Code = "843", Name = "دوگنبدان" },
                    new IntamediaCity() { Code = "844", Name = "دامغان" },
                    new IntamediaCity() { Code = "845", Name = "امیریه" },
                    new IntamediaCity() { Code = "846", Name = "دیباج" },
                    new IntamediaCity() { Code = "847", Name = "سرخه" },
                    new IntamediaCity() { Code = "848", Name = "سمنان" },
                    new IntamediaCity() { Code = "849", Name = "شهمیرزاد" },
                    new IntamediaCity() { Code = "850", Name = "مهدیشهر" },
                    new IntamediaCity() { Code = "851", Name = "بسطام" },
                    new IntamediaCity() { Code = "852", Name = "بیارجمند" },
                    new IntamediaCity() { Code = "853", Name = "شاهرود" },
                    new IntamediaCity() { Code = "854", Name = "کلاته خیج" },
                    new IntamediaCity() { Code = "855", Name = "مجن" },
                    new IntamediaCity() { Code = "856", Name = "میامی" },
                    new IntamediaCity() { Code = "857", Name = "آرادان" },
                    new IntamediaCity() { Code = "858", Name = "ایوانکی" },
                    new IntamediaCity() { Code = "859", Name = "گرمسار" },
                    new IntamediaCity() { Code = "860", Name = "بوشهر" },
                    new IntamediaCity() { Code = "861", Name = "چغادک" },
                    new IntamediaCity() { Code = "862", Name = "خارک" },
                    new IntamediaCity() { Code = "863", Name = "اهرم" },
                    new IntamediaCity() { Code = "864", Name = "دلوار" },
                    new IntamediaCity() { Code = "865", Name = "جم" },
                    new IntamediaCity() { Code = "866", Name = "ریز" },
                    new IntamediaCity() { Code = "867", Name = "آبپخش" },
                    new IntamediaCity() { Code = "868", Name = "برازجان" },
                    new IntamediaCity() { Code = "869", Name = "تنگ ارم" },
                    new IntamediaCity() { Code = "870", Name = "دالکی" },
                    new IntamediaCity() { Code = "871", Name = "سعدآباد" },
                    new IntamediaCity() { Code = "872", Name = "شبانکاره" },
                    new IntamediaCity() { Code = "873", Name = "کلمه" },
                    new IntamediaCity() { Code = "874", Name = "وحدتیه" },
                    new IntamediaCity() { Code = "875", Name = "خورموج" },
                    new IntamediaCity() { Code = "876", Name = "کاکی" },
                    new IntamediaCity() { Code = "877", Name = "آبدان" },
                    new IntamediaCity() { Code = "878", Name = "بردخون" },
                    new IntamediaCity() { Code = "879", Name = "بندردیر" },
                    new IntamediaCity() { Code = "880", Name = "امام حسن" },
                    new IntamediaCity() { Code = "881", Name = "بندر دیلم" },
                    new IntamediaCity() { Code = "882", Name = "بندرکنگان" },
                    new IntamediaCity() { Code = "883", Name = "بنک" },
                    new IntamediaCity() { Code = "885", Name = "عسلویه" },
                    new IntamediaCity() { Code = "886", Name = "نخل تقی" },
                    new IntamediaCity() { Code = "887", Name = "بندر ریگ" },
                    new IntamediaCity() { Code = "888", Name = "بندرگناوه" },
                    new IntamediaCity() { Code = "889", Name = "ابهر" },
                    new IntamediaCity() { Code = "890", Name = "سلطانیه" },
                    new IntamediaCity() { Code = "891", Name = "صائین قلعه" },
                    new IntamediaCity() { Code = "892", Name = "هیدج" },
                    new IntamediaCity() { Code = "893", Name = "حلب" },
                    new IntamediaCity() { Code = "894", Name = "زرین آباد" },
                    new IntamediaCity() { Code = "895", Name = "زرین رود" },
                    new IntamediaCity() { Code = "896", Name = "سجاس" },
                    new IntamediaCity() { Code = "897", Name = "قیدار" },
                    new IntamediaCity() { Code = "898", Name = "گرماب" },
                    new IntamediaCity() { Code = "899", Name = "خرمدره" },
                    new IntamediaCity() { Code = "900", Name = "زنجان" },
                    new IntamediaCity() { Code = "901", Name = "آب بر" },
                    new IntamediaCity() { Code = "902", Name = "چورزق" },
                    new IntamediaCity() { Code = "903", Name = "دندی" },
                    new IntamediaCity() { Code = "904", Name = "ماهنشان" },
                    new IntamediaCity() { Code = "905", Name = "آبدانان" },
                    new IntamediaCity() { Code = "906", Name = "مورموری" },
                    new IntamediaCity() { Code = "907", Name = "ایلام" },
                    new IntamediaCity() { Code = "908", Name = "چوار" },
                    new IntamediaCity() { Code = "909", Name = "ایوان" },
                    new IntamediaCity() { Code = "910", Name = "زرنه" },
                    new IntamediaCity() { Code = "911", Name = "بدره" },
                    new IntamediaCity() { Code = "912", Name = "دره شهر" },
                    new IntamediaCity() { Code = "913", Name = "پهله" },
                    new IntamediaCity() { Code = "914", Name = "دهلران" },
                    new IntamediaCity() { Code = "915", Name = "موسیان" },
                    new IntamediaCity() { Code = "916", Name = "میمه" },
                    new IntamediaCity() { Code = "917", Name = "آسمان آباد" },
                    new IntamediaCity() { Code = "918", Name = "توحید" },
                    new IntamediaCity() { Code = "919", Name = "سرآبله" },
                    new IntamediaCity() { Code = "920", Name = "لومار" },
                    new IntamediaCity() { Code = "921", Name = "ارکواز" },
                    new IntamediaCity() { Code = "922", Name = "صالح آباد" },
                    new IntamediaCity() { Code = "923", Name = "مهران" },
                    new IntamediaCity() { Code = "924", Name = "آران و بیدگل" },
                    new IntamediaCity() { Code = "925", Name = "ابوزیدآباد" },
                    new IntamediaCity() { Code = "926", Name = "سفیدشهر" },
                    new IntamediaCity() { Code = "927", Name = "نوش آباد" },
                    new IntamediaCity() { Code = "928", Name = "اردستان" },
                    new IntamediaCity() { Code = "929", Name = "زواره" },
                    new IntamediaCity() { Code = "930", Name = "مهاباد" },
                    new IntamediaCity() { Code = "931", Name = "اژیه" },
                    new IntamediaCity() { Code = "932", Name = "اصفهان" },
                    new IntamediaCity() { Code = "933", Name = "بهارستان" },
                    new IntamediaCity() { Code = "934", Name = "تودشک" },
                    new IntamediaCity() { Code = "935", Name = "حسن آباد" },
                    new IntamediaCity() { Code = "936", Name = "خوراسگان" },
                    new IntamediaCity() { Code = "937", Name = "سگزی" },
                    new IntamediaCity() { Code = "938", Name = "کوهپایه" },
                    new IntamediaCity() { Code = "939", Name = "محمد آباد" },
                    new IntamediaCity() { Code = "940", Name = "نصرآباد" },
                    new IntamediaCity() { Code = "941", Name = "نیک آباد" },
                    new IntamediaCity() { Code = "942", Name = "ورزنه" },
                    new IntamediaCity() { Code = "943", Name = "هرند" },
                    new IntamediaCity() { Code = "944", Name = "حبیب آباد" },
                    new IntamediaCity() { Code = "945", Name = "خورزوق" },
                    new IntamediaCity() { Code = "946", Name = "دستگرد" },
                    new IntamediaCity() { Code = "947", Name = "دولت آباد" },
                    new IntamediaCity() { Code = "948", Name = "شاهین شهر" },
                    new IntamediaCity() { Code = "949", Name = "کمشچه" },
                    new IntamediaCity() { Code = "950", Name = "گز برخوار" },
                    new IntamediaCity() { Code = "951", Name = "میمه" },
                    new IntamediaCity() { Code = "952", Name = "وزوان" },
                    new IntamediaCity() { Code = "953", Name = "تیران" },
                    new IntamediaCity() { Code = "954", Name = "رضوانشهر" },
                    new IntamediaCity() { Code = "955", Name = "عسگران" },
                    new IntamediaCity() { Code = "956", Name = "چادگان" },
                    new IntamediaCity() { Code = "957", Name = "رزوه" },
                    new IntamediaCity() { Code = "958", Name = "خمینی شهر" },
                    new IntamediaCity() { Code = "959", Name = "درچه پیاز" },
                    new IntamediaCity() { Code = "960", Name = "کوشک" },
                    new IntamediaCity() { Code = "961", Name = "خوانسار" },
                    new IntamediaCity() { Code = "962", Name = "حنا" },
                    new IntamediaCity() { Code = "963", Name = "سمیرم" },
                    new IntamediaCity() { Code = "964", Name = "کمه" },
                    new IntamediaCity() { Code = "965", Name = "ونک" },
                    new IntamediaCity() { Code = "966", Name = "دهاقان" },
                    new IntamediaCity() { Code = "967", Name = "شهرضا" },
                    new IntamediaCity() { Code = "968", Name = "منظریه" },
                    new IntamediaCity() { Code = "969", Name = "افوس" },
                    new IntamediaCity() { Code = "970", Name = "بوئین و میاندشت" },
                    new IntamediaCity() { Code = "971", Name = "داران" },
                    new IntamediaCity() { Code = "972", Name = "دامنه" },
                    new IntamediaCity() { Code = "973", Name = "برف انبار" },
                    new IntamediaCity() { Code = "974", Name = "فریدونشهر" },
                    new IntamediaCity() { Code = "975", Name = "ابریشم" },
                    new IntamediaCity() { Code = "976", Name = "ایمانشهر" },
                    new IntamediaCity() { Code = "977", Name = "بهاران شهر" },
                    new IntamediaCity() { Code = "978", Name = "پیربکران" },
                    new IntamediaCity() { Code = "979", Name = "فلاورجان" },
                    new IntamediaCity() { Code = "980", Name = "قهدریجان" },
                    new IntamediaCity() { Code = "981", Name = "کلیشادوسودرجان" },
                    new IntamediaCity() { Code = "982", Name = "برزک" },
                    new IntamediaCity() { Code = "983", Name = "جوشقان و کامو" },
                    new IntamediaCity() { Code = "984", Name = "قمصر" },
                    new IntamediaCity() { Code = "985", Name = "کاشان" },
                    new IntamediaCity() { Code = "986", Name = "مشکات" },
                    new IntamediaCity() { Code = "987", Name = "نیاسر" },
                    new IntamediaCity() { Code = "988", Name = "گلپایگان" },
                    new IntamediaCity() { Code = "989", Name = "گلشهر" },
                    new IntamediaCity() { Code = "990", Name = "گوگد" },
                    new IntamediaCity() { Code = "991", Name = "باغ بهادران" },
                    new IntamediaCity() { Code = "992", Name = "چرمهین" },
                    new IntamediaCity() { Code = "993", Name = "چمگردان" },
                    new IntamediaCity() { Code = "994", Name = "زاینده رود" },
                    new IntamediaCity() { Code = "995", Name = "زرین شهر" },
                    new IntamediaCity() { Code = "996", Name = "سده لنجان" },
                    new IntamediaCity() { Code = "997", Name = "فولادشهر" },
                    new IntamediaCity() { Code = "998", Name = "ورنامخواست" },
                    new IntamediaCity() { Code = "999", Name = "دیزیچه" },
                    new IntamediaCity() { Code = "1000", Name = "زیباشهر" },
                    new IntamediaCity() { Code = "1001", Name = "طالخونچه" },
                    new IntamediaCity() { Code = "1002", Name = "کرکوند" },
                    new IntamediaCity() { Code = "1003", Name = "مبارکه" },
                    new IntamediaCity() { Code = "1004", Name = "انارک" },
                    new IntamediaCity() { Code = "1005", Name = "جندق" },
                    new IntamediaCity() { Code = "1006", Name = "خور" },
                    new IntamediaCity() { Code = "1007", Name = "نائین" },
                    new IntamediaCity() { Code = "1008", Name = "دهق" },
                    new IntamediaCity() { Code = "1009", Name = "علویجه" },
                    new IntamediaCity() { Code = "1010", Name = "کهریزسنگ" },
                    new IntamediaCity() { Code = "1011", Name = "گلدشت" },
                    new IntamediaCity() { Code = "1012", Name = "نجف آباد" },
                    new IntamediaCity() { Code = "1013", Name = "بادرود" },
                    new IntamediaCity() { Code = "1014", Name = "خالدآ باد" },
                    new IntamediaCity() { Code = "1015", Name = "نطنز" },
                    new IntamediaCity() { Code = "1016", Name = "نصیرآباد" },
                    new IntamediaCity() { Code = "1017", Name = "ری" },
                    new IntamediaCity() { Code = "1019", Name = "گلسار" },
                    new IntamediaCity() { Code = "1021", Name = "سلفچگان" },
                    new IntamediaCity() { Code = "1022", Name = "جوزدان" },
                    new IntamediaCity() { Code = "1023", Name = "گرگاب" },
                    new IntamediaCity() { Code = "1024", Name = "لای بید" },
                    new IntamediaCity() { Code = "1025", Name = "قهجاورستان" },
                    new IntamediaCity() { Code = "1026", Name = "قره ضیاءالدین" },
                    new IntamediaCity() { Code = "1027", Name = "تنکمان" },
                    new IntamediaCity() { Code = "1028", Name = "آسارا" },
                    new IntamediaCity() { Code = "1029", Name = "جلین" },
                    new IntamediaCity() { Code = "1031", Name = "تفرش" },
                    new IntamediaCity() { Code = "1032", Name = "لاله زار" },
                    new IntamediaCity() { Code = "1033", Name = "دشتکار" },
                    new IntamediaCity() { Code = "1034", Name = "خواجو شهر" },
                    new IntamediaCity() { Code = "1035", Name = "قیر" },
                    new IntamediaCity() { Code = "1036", Name = "مبارک اباد" },
                    new IntamediaCity() { Code = "1037", Name = "امام شهر" },
                    new IntamediaCity() { Code = "1038", Name = "ارسک" },
                    new IntamediaCity() { Code = "1039", Name = "گله دار" },
                    new IntamediaCity() { Code = "1040", Name = "گرمه" },
                    new IntamediaCity() { Code = "1041", Name = "هماشهر" },
                    new IntamediaCity() { Code = "1042", Name = "کلارآباد" },
                    new IntamediaCity() { Code = "1043", Name = "کره ای" },
                    new IntamediaCity() { Code = "1044", Name = "اچاچی" },
                    new IntamediaCity() { Code = "1045", Name = "مزایجان" },
                    new IntamediaCity() { Code = "1100", Name = "تیمورلو" },
                    new IntamediaCity() { Code = "1101", Name = "کوت عبداله" },
                    new IntamediaCity() { Code = "1102", Name = "طرقبه" },
                    new IntamediaCity() { Code = "1103", Name = "شاندیز" },
                    new IntamediaCity() { Code = "1104", Name = "کوزه کنان" },
                    new IntamediaCity() { Code = "1105", Name = "جوان قلعه" },
                    new IntamediaCity() { Code = "1106", Name = "مبارک شهر" },
                    new IntamediaCity() { Code = "1107", Name = "کلوانق" },
                    new IntamediaCity() { Code = "1108", Name = "نقنه" },
                    new IntamediaCity() { Code = "1109", Name = "دستنا" },
                    new IntamediaCity() { Code = "1110", Name = "وردنجان" },
                    new IntamediaCity() { Code = "1111", Name = "هارونی" },
                    new IntamediaCity() { Code = "1112", Name = "گوجان" },
                    new IntamediaCity() { Code = "1113", Name = "پردنجان" },
                    new IntamediaCity() { Code = "1114", Name = "چلیچه" },
                    new IntamediaCity() { Code = "1115", Name = "منج" },
                    new IntamediaCity() { Code = "1116", Name = "سردشت" },
                    new IntamediaCity() { Code = "1117", Name = "کاج" },
                    new IntamediaCity() { Code = "1118", Name = "دشتک" },
                    new IntamediaCity() { Code = "1119", Name = "بازفت" },
                    new IntamediaCity() { Code = "1120", Name = "سرخون" },
                    new IntamediaCity() { Code = "1121", Name = "صمصامی" },
                    new IntamediaCity() { Code = "1122", Name = "شول آباد" },
                    new IntamediaCity() { Code = "1124", Name = "هفت چشمه" },
                    new IntamediaCity() { Code = "1125", Name = "کوشکنار" },
                    new IntamediaCity() { Code = "1126", Name = "محمدشهر" },
                    new IntamediaCity() { Code = "1127", Name = "پارسیان" },
                    new IntamediaCity() { Code = "1128", Name = "دشتی" },
                    new IntamediaCity() { Code = "1130", Name = "آجین" },
                    new IntamediaCity() { Code = "1131", Name = "مهاجران" },
                    new IntamediaCity() { Code = "1132", Name = "کرفس" },
                    new IntamediaCity() { Code = "1134", Name = "برزول" },
                    new IntamediaCity() { Code = "1135", Name = "پیرتاج" },
                    new IntamediaCity() { Code = "1136", Name = "توپ آغاج" },
                    new IntamediaCity() { Code = "1137", Name = "بلبان آباد" },
                    new IntamediaCity() { Code = "1138", Name = "برده رشه" },
                    new IntamediaCity() { Code = "1139", Name = "کانی دینار" },
                    new IntamediaCity() { Code = "1140", Name = "اورامان تخت" },
                    new IntamediaCity() { Code = "1141", Name = "ایور" },
                    new IntamediaCity() { Code = "1142", Name = "تازه کند" },
                    new IntamediaCity() { Code = "1143", Name = "اسلام اباد" },
                    new IntamediaCity() { Code = "1144", Name = "فخراباد" },
                    new IntamediaCity() { Code = "1145", Name = "مرادلو" },
                    new IntamediaCity() { Code = "1146", Name = "قصابه" },
                    new IntamediaCity() { Code = "1147", Name = "بفروییه" },
                    new IntamediaCity() { Code = "1148", Name = "سردشت" },
                    new IntamediaCity() { Code = "1149", Name = "گوهران" },
                    new IntamediaCity() { Code = "1150", Name = "قهستان" },
                    new IntamediaCity() { Code = "1151", Name = "طبس مسینا" },
                    new IntamediaCity() { Code = "1152", Name = "گزیک" },
                    new IntamediaCity() { Code = "1153", Name = "محمدان" },
                    new IntamediaCity() { Code = "1156", Name = "شهرک علی اکبر" },
                    new IntamediaCity() { Code = "1157", Name = "سوران" },
                    new IntamediaCity() { Code = "1158", Name = "محمدی" },
                    new IntamediaCity() { Code = "1159", Name = "گشت" },
                    new IntamediaCity() { Code = "1160", Name = "سهند" },
                    new IntamediaCity() { Code = "1161", Name = "تازیان پایین" },
                    new IntamediaCity() { Code = "1162", Name = "تخت" },
                    new IntamediaCity() { Code = "1163", Name = "قلعه قاضی" },
                    new IntamediaCity() { Code = "1164", Name = "لمزان" },
                    new IntamediaCity() { Code = "1167", Name = "لیردف" },
                    new IntamediaCity() { Code = "1168", Name = "سرگز" },
                    new IntamediaCity() { Code = "1169", Name = "رویدر" },
                    new IntamediaCity() { Code = "1170", Name = "بیکاء" },
                    new IntamediaCity() { Code = "1171", Name = "کوهستک" },
                    new IntamediaCity() { Code = "1172", Name = "گروک" },
                    new IntamediaCity() { Code = "1173", Name = "سندرک" },
                    new IntamediaCity() { Code = "1174", Name = "تیرور" },
                    new IntamediaCity() { Code = "1175", Name = "هشتبندئ" },
                    new IntamediaCity() { Code = "1176", Name = "احمد آباد مستوفی" },
                    new IntamediaCity() { Code = "1177", Name = "فرون اباد" },
                    new IntamediaCity() { Code = "1178", Name = "فردیس" },
                    new IntamediaCity() { Code = "1179", Name = "آزادی" },
                    new IntamediaCity() { Code = "1180", Name = "چم گلک" },
                    new IntamediaCity() { Code = "1181", Name = "بیدروبه" },
                    new IntamediaCity() { Code = "1182", Name = "چویبده" },
                    new IntamediaCity() { Code = "1183", Name = "میداود" },
                    new IntamediaCity() { Code = "1184", Name = "منصوریه" },
                    new IntamediaCity() { Code = "1185", Name = "تشان" },
                    new IntamediaCity() { Code = "1186", Name = "مقاومت" },
                    new IntamediaCity() { Code = "1187", Name = "شمس آباد" },
                    new IntamediaCity() { Code = "1188", Name = "حمزه" },
                    new IntamediaCity() { Code = "1189", Name = "سیاه منصور" },
                    new IntamediaCity() { Code = "1190", Name = "الهایی" },
                    new IntamediaCity() { Code = "1191", Name = "چغامیش" },
                    new IntamediaCity() { Code = "1193", Name = "کوت سیدنعیم" },
                    new IntamediaCity() { Code = "1194", Name = "ابوحمیظه" },
                    new IntamediaCity() { Code = "1195", Name = "مشراگه" },
                    new IntamediaCity() { Code = "1196", Name = "خنافره" },
                    new IntamediaCity() { Code = "1197", Name = "دارخوین" },
                    new IntamediaCity() { Code = "1198", Name = "حر" },
                    new IntamediaCity() { Code = "1199", Name = "شرافت" },
                    new IntamediaCity() { Code = "1200", Name = "فتح المبین" },
                    new IntamediaCity() { Code = "1201", Name = "سرداران" },
                    new IntamediaCity() { Code = "1202", Name = "ترکالکی" },
                    new IntamediaCity() { Code = "1203", Name = "گوریه" },
                    new IntamediaCity() { Code = "1204", Name = "سماله" },
                    new IntamediaCity() { Code = "1205", Name = "صالح شهر" },
                    new IntamediaCity() { Code = "1206", Name = "آبژدان" },
                    new IntamediaCity() { Code = "1207", Name = "گلگیر" },
                    new IntamediaCity() { Code = "1208", Name = "جنت مکان" },
                    new IntamediaCity() { Code = "1209", Name = "دژکرد" },
                    new IntamediaCity() { Code = "1210", Name = "مادرسلیمان" },
                    new IntamediaCity() { Code = "1211", Name = "دوزه" },
                    new IntamediaCity() { Code = "1212", Name = "فدامی" },
                    new IntamediaCity() { Code = "1213", Name = "شهرپیر" },
                    new IntamediaCity() { Code = "1214", Name = "دوبرجی" },
                    new IntamediaCity() { Code = "1216", Name = "دبیران" },
                    new IntamediaCity() { Code = "1217", Name = "سلطان شهر" },
                    new IntamediaCity() { Code = "1219", Name = "کوهنجان" },
                    new IntamediaCity() { Code = "1220", Name = "شهرصدرا" },
                    new IntamediaCity() { Code = "1221", Name = "خانه زنیان" },
                    new IntamediaCity() { Code = "1222", Name = "نوجین" },
                    new IntamediaCity() { Code = "1223", Name = "دهرم" },
                    new IntamediaCity() { Code = "1224", Name = "قره بلاغ" },
                    new IntamediaCity() { Code = "1225", Name = "میانشهر" },
                    new IntamediaCity() { Code = "1226", Name = "لطیفی" },
                    new IntamediaCity() { Code = "1227", Name = "عمادده" },
                    new IntamediaCity() { Code = "1228", Name = "خانیمن" },
                    new IntamediaCity() { Code = "1229", Name = "رامجرد" },
                    new IntamediaCity() { Code = "1230", Name = "کوپن" },
                    new IntamediaCity() { Code = "1231", Name = "خومه زار" },
                    new IntamediaCity() { Code = "1232", Name = "قطرویه" },
                    new IntamediaCity() { Code = "1233", Name = "هنزا" },
                    new IntamediaCity() { Code = "1234", Name = "گنبکی" },
                    new IntamediaCity() { Code = "1235", Name = "بلوک" },
                    new IntamediaCity() { Code = "1237", Name = "امین شهر" },
                    new IntamediaCity() { Code = "1238", Name = "صفائیه" },
                    new IntamediaCity() { Code = "1239", Name = "زهکلوت" },
                    new IntamediaCity() { Code = "1240", Name = "خورسند" },
                    new IntamediaCity() { Code = "1241", Name = "خاتون اباد" },
                    new IntamediaCity() { Code = "1242", Name = "جوزم" },
                    new IntamediaCity() { Code = "1243", Name = "دوساری" },
                    new IntamediaCity() { Code = "1244", Name = "شهراباد" },
                    new IntamediaCity() { Code = "1245", Name = "احمدابادصولت" },
                    new IntamediaCity() { Code = "1246", Name = "گلمکان" },
                    new IntamediaCity() { Code = "1247", Name = "گلبهار" },
                    new IntamediaCity() { Code = "1248", Name = "مشهد ثامن" },
                    new IntamediaCity() { Code = "1249", Name = "شادمهر" },
                    new IntamediaCity() { Code = "1250", Name = "همت آباد" },
                    new IntamediaCity() { Code = "1251", Name = "درود" },
                    new IntamediaCity() { Code = "1252", Name = "بار" },
                    new IntamediaCity() { Code = "1253", Name = "چناران شهر" },
                    new IntamediaCity() { Code = "1254", Name = "زیارت" },
                    new IntamediaCity() { Code = "1255", Name = "قوشخانه" },
                    new IntamediaCity() { Code = "1256", Name = "تیتکانلو" },
                    new IntamediaCity() { Code = "1257", Name = "آوا" },
                    new IntamediaCity() { Code = "1258", Name = "تاتارعلیا" },
                    new IntamediaCity() { Code = "1259", Name = "مزرعه" },
                    new IntamediaCity() { Code = "1260", Name = "سنگدوین" },
                    new IntamediaCity() { Code = "1261", Name = "فراغی" },
                    new IntamediaCity() { Code = "1262", Name = "شریفیه" },
                    new IntamediaCity() { Code = "1264", Name = "جاورسیان" },
                    new IntamediaCity() { Code = "1265", Name = "ساروق" },
                    new IntamediaCity() { Code = "1266", Name = "کارچان" },
                    new IntamediaCity() { Code = "1267", Name = "آوه" },
                    new IntamediaCity() { Code = "1268", Name = "مهاجران" },
                    new IntamediaCity() { Code = "1269", Name = "شهباز" },
                    new IntamediaCity() { Code = "1270", Name = "خشکرود" },
                    new IntamediaCity() { Code = "1271", Name = "امامزاده عبدالله" },
                    new IntamediaCity() { Code = "1272", Name = "شیرود" },
                    new IntamediaCity() { Code = "1273", Name = "پایین هولار" },
                    new IntamediaCity() { Code = "1274", Name = "ارطه" },
                    new IntamediaCity() { Code = "1275", Name = "پول" },
                    new IntamediaCity() { Code = "1276", Name = "کجور" },
                    new IntamediaCity() { Code = "1277", Name = "هادی شهر" },
                    new IntamediaCity() { Code = "1278", Name = "هچیرود" },
                    new IntamediaCity() { Code = "1279", Name = "لولمان" },
                    new IntamediaCity() { Code = "1280", Name = "ماکلوان" },
                    new IntamediaCity() { Code = "1282", Name = "زرآباد" },
                    new IntamediaCity() { Code = "1283", Name = "کشاورز" },
                    new IntamediaCity() { Code = "1284", Name = "زرآباد" },
                    new IntamediaCity() { Code = "1285", Name = "قطور" },
                    new IntamediaCity() { Code = "1286", Name = "نازک علیا" },
                    new IntamediaCity() { Code = "1287", Name = "مرگنلر" },
                    new IntamediaCity() { Code = "1288", Name = "خلیفان" },
                    new IntamediaCity() { Code = "1289", Name = "گوگ تپه" },
                    new IntamediaCity() { Code = "1290", Name = "بانوره" },
                    new IntamediaCity() { Code = "1291", Name = "نوسود" },
                    new IntamediaCity() { Code = "1292", Name = "گودین" },
                    new IntamediaCity() { Code = "1294", Name = "شاهو" },
                    new IntamediaCity() { Code = "1295", Name = "ریجاب" },
                    new IntamediaCity() { Code = "1296", Name = "مادوان" },
                    new IntamediaCity() { Code = "1297", Name = "چیتاب" },
                    new IntamediaCity() { Code = "1298", Name = "پاتاوه" },
                    new IntamediaCity() { Code = "1299", Name = "سرفاریاب" },
                    new IntamediaCity() { Code = "1300", Name = "کلاته" },
                    new IntamediaCity() { Code = "1301", Name = "درجزین" },
                    new IntamediaCity() { Code = "1302", Name = "رودیان" },
                    new IntamediaCity() { Code = "1303", Name = "کهن آباد" },
                    new IntamediaCity() { Code = "1304", Name = "عالی شهر" },
                    new IntamediaCity() { Code = "1305", Name = "آباد" },
                    new IntamediaCity() { Code = "1306", Name = "انارستان" },
                    new IntamediaCity() { Code = "1307", Name = "بوشکان" },
                    new IntamediaCity() { Code = "1308", Name = "بادوله" },
                    new IntamediaCity() { Code = "1309", Name = "شنبه" },
                    new IntamediaCity() { Code = "1310", Name = "بردستان" },
                    new IntamediaCity() { Code = "1311", Name = "دوراهک" },
                    new IntamediaCity() { Code = "1312", Name = "سیراف" },
                    new IntamediaCity() { Code = "1313", Name = "سهرورد" },
                    new IntamediaCity() { Code = "1314", Name = "کرسف" },
                    new IntamediaCity() { Code = "1315", Name = "نوربهار" },
                    new IntamediaCity() { Code = "1316", Name = "نیک پی" },
                    new IntamediaCity() { Code = "1317", Name = "ارمغانخانه" },
                    new IntamediaCity() { Code = "1318", Name = "سراب باغ" },
                    new IntamediaCity() { Code = "1319", Name = "ماژین" },
                    new IntamediaCity() { Code = "1320", Name = "شباب" },
                    new IntamediaCity() { Code = "1321", Name = "بلاوه" },
                    new IntamediaCity() { Code = "1322", Name = "دلگشا" },
                    new IntamediaCity() { Code = "1323", Name = "مهر" },
                    new IntamediaCity() { Code = "1324", Name = "شاپورآباد" },
                    new IntamediaCity() { Code = "1325", Name = "سین" },
                    new IntamediaCity() { Code = "1326", Name = "اصغرآباد" },
                    new IntamediaCity() { Code = "1327", Name = "گلشن" },
                    new IntamediaCity() { Code = "1328", Name = "زازران" },
                    new IntamediaCity() { Code = "1329", Name = "کامو و چوگان" },
                    new IntamediaCity() { Code = "1330", Name = "باغشاد" },
                    new IntamediaCity() { Code = "1331", Name = "مجلسی" },
                    new IntamediaCity() { Code = "1332", Name = "فرخی" },
                    new IntamediaCity() { Code = "1333", Name = "بافران" },
                    new IntamediaCity() { Code = "1334", Name = "طرق رود" },
                    new IntamediaCity() { Code = "1335", Name = "پرند" },
                    new IntamediaCity() { Code = "1336", Name = "تجریش" },
                    new IntamediaCity() { Code = "1338", Name = "زیار" },
                    new IntamediaCity() { Code = "1339", Name = "هماشهر" },
                    new IntamediaCity() { Code = "1340", Name = "بلورد" },
                    new IntamediaCity() { Code = "1341", Name = "اسیر" },
                    new IntamediaCity() { Code = "1342", Name = "خوزی" },
                    new IntamediaCity() { Code = "1343", Name = "حسامی" },
                    new IntamediaCity() { Code = "1344", Name = "اسلام شهر آق گل" },
                    new IntamediaCity() { Code = "1345", Name = "دیزج دیز" },
                    new IntamediaCity() { Code = "1346", Name = "صباشهر" },
                    new IntamediaCity() { Code = "1347", Name = "حسن اباد" },
                    new IntamediaCity() { Code = "1348", Name = "بابامنیر" },
                    new IntamediaCity() { Code = "1349", Name = "ویسیان" },
                    new IntamediaCity() { Code = "1400", Name = "شمشک" },
                    new IntamediaCity() { Code = "1401", Name = "قرق" },
                    new IntamediaCity() { Code = "1500", Name = "چاف و چمخاله" },
                    new IntamediaCity() { Code = "1501", Name = "خنجین" },
                    new IntamediaCity() { Code = "1504", Name = "شلمان" },
                    new IntamediaCity() { Code = "1506", Name = "صغاد" },
                    new IntamediaCity() { Code = "1507", Name = "مینادشت" },
                    new IntamediaCity() { Code = "1508", Name = "اشترجان" },
                    new IntamediaCity() { Code = "1509", Name = "آبیز" },
                    new IntamediaCity() { Code = "1510", Name = "درح" },
                    new IntamediaCity() { Code = "1511", Name = "رضوان" },
                    new IntamediaCity() { Code = "1512", Name = "جزینک" },
                    new IntamediaCity() { Code = "1513", Name = "نوک اباد" },
                    new IntamediaCity() { Code = "1514", Name = "پارود" },
                    new IntamediaCity() { Code = "1515", Name = "سیب" },
                    new IntamediaCity() { Code = "1516", Name = "گتیج" },
                    new IntamediaCity() { Code = "1517", Name = "ساربوک" },
                    new IntamediaCity() { Code = "1518", Name = "ریگ ملک" },
                    new IntamediaCity() { Code = "1519", Name = "لادیز" },
                    new IntamediaCity() { Code = "1520", Name = "قرقری" },
                    new IntamediaCity() { Code = "1521", Name = "کوره" },
                    new IntamediaCity() { Code = "1522", Name = "خیراباد" },
                    new IntamediaCity() { Code = "1523", Name = "معزابادجابری" },
                    new IntamediaCity() { Code = "1524", Name = "محمله" },
                    new IntamediaCity() { Code = "1525", Name = "پاسخن" },
                    new IntamediaCity() { Code = "1526", Name = "رستاق" },
                    new IntamediaCity() { Code = "1527", Name = "رحمت آباد" },
                    new IntamediaCity() { Code = "1528", Name = "اکبرآباد" },
                    new IntamediaCity() { Code = "1529", Name = "طسوج" },
                    new IntamediaCity() { Code = "1530", Name = "مظفری" },
                    new IntamediaCity() { Code = "1531", Name = "ارد" },
                    new IntamediaCity() { Code = "1532", Name = "دهکویه" },
                    new IntamediaCity() { Code = "1533", Name = "چاه ورز" },
                    new IntamediaCity() { Code = "1534", Name = "خیرگو" },
                    new IntamediaCity() { Code = "1535", Name = "زنگی آباد" },
                    new IntamediaCity() { Code = "1536", Name = "فاروق" },
                    new IntamediaCity() { Code = "1537", Name = "فتح آباد" },
                    new IntamediaCity() { Code = "1538", Name = "فال" },
                    new IntamediaCity() { Code = "1539", Name = "کردکندی" },
                    new IntamediaCity() { Code = "1540", Name = "خوشه مهر" },
                    new IntamediaCity() { Code = "1541", Name = "داریان" },
                    new IntamediaCity() { Code = "1542", Name = "علیشاه (علی آباد)" },
                    new IntamediaCity() { Code = "1543", Name = "دیزج حسین بیگ" },
                    new IntamediaCity() { Code = "1544", Name = "اربطان" },
                    new IntamediaCity() { Code = "1545", Name = "لاجان" },
                    new IntamediaCity() { Code = "1546", Name = "تازه کندنصرت آباد" },
                    new IntamediaCity() { Code = "1547", Name = "حاجیلار" },
                    new IntamediaCity() { Code = "1548", Name = "نلاس" },
                    new IntamediaCity() { Code = "1549", Name = "یولاگلدی" },
                    new IntamediaCity() { Code = "1550", Name = "بکتاش" },
                    new IntamediaCity() { Code = "1551", Name = "بابکان" },
                    new IntamediaCity() { Code = "1552", Name = "فرح آباد" },
                    new IntamediaCity() { Code = "1553", Name = "آستانه سرا" },
                    new IntamediaCity() { Code = "1554", Name = "طبقده" },
                    new IntamediaCity() { Code = "1555", Name = "پیربازار" },
                    new IntamediaCity() { Code = "1556", Name = "خمام" },
                    new IntamediaCity() { Code = "1557", Name = "قلعه نوعلیا" },
                    new IntamediaCity() { Code = "1558", Name = "مهردشت" },
                    new IntamediaCity() { Code = "1559", Name = "گلبهار" },
                    new IntamediaCity() { Code = "1560", Name = "یوسف آباد" },
                    new IntamediaCity() { Code = "1561", Name = "الوان" },
                    ];
            }
        }

    }
}
