namespace TadbirTaxService.Models.Intamedia
{
    public class IntamediaCountry
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }

        public static List<IntamediaCountry> Countries
        {
            get
            {
                return [
                new IntamediaCountry() { Code = "001", Name = "آذربایجان", EnglishName = "AZARBAIJAN" },
                new IntamediaCountry() { Code = "002", Name = "آرژانتین", EnglishName = "ARGENTINA" },
                new IntamediaCountry() { Code = "003", Name = "آفریقای جنوبی", EnglishName = "SOUTH AFRICA" },
                new IntamediaCountry() { Code = "004", Name = "آفریقای مرکزی", EnglishName = "CENTRAL AFRICA" },
                new IntamediaCountry() { Code = "005", Name = "آلبانی", EnglishName = "ALBANIA" },
                new IntamediaCountry() { Code = "006", Name = "آلمان", EnglishName = "GERMANY(DEUTSCHLAND)" },
                new IntamediaCountry() { Code = "007", Name = "آنتیگوا و باربودا", EnglishName = "ANTIGUA & BARBUDA" },
                new IntamediaCountry() { Code = "008", Name = "آندورا", EnglishName = "ANDORRA" },
                new IntamediaCountry() { Code = "009", Name = "آنگولا", EnglishName = "ANGOLA" },
                new IntamediaCountry() { Code = "011", Name = "اتیوپی (حبشه)", EnglishName = "ETHIOPIA" },
                new IntamediaCountry() { Code = "012", Name = "اردن", EnglishName = "JORDAN" },
                new IntamediaCountry() { Code = "013", Name = "ارمنستان", EnglishName = "ARMENIA" },
                new IntamediaCountry() { Code = "014", Name = "اروگوئه", EnglishName = "URUGUAY" },
                new IntamediaCountry() { Code = "015", Name = "اریتره", EnglishName = "ERITREA" },
                new IntamediaCountry() { Code = "016", Name = "ازبکستان", EnglishName = "UZBEKISTAN" },
                new IntamediaCountry() { Code = "017", Name = "اسپانیا", EnglishName = "SPAIN" },
                new IntamediaCountry() { Code = "018", Name = "استرالیا", EnglishName = "AUSTRALIA" },
                new IntamediaCountry() { Code = "019", Name = "استونی", EnglishName = "ESTONIA EESTI" },
                new IntamediaCountry() { Code = "020", Name = "اسلوواکی", EnglishName = "SLOVAKIA" },
                new IntamediaCountry() { Code = "021", Name = "اسلوونی", EnglishName = "SLOVENIA" },
                new IntamediaCountry() { Code = "022", Name = "افغانستان", EnglishName = "AFGHANISTAN" },
                new IntamediaCountry() { Code = "023", Name = "اکوادور", EnglishName = "ECUADOR" },
                new IntamediaCountry() { Code = "024", Name = "الجزایر", EnglishName = "ALGERIA" },
                new IntamediaCountry() { Code = "025", Name = "السالوادور", EnglishName = "ELSALVADOR" },
                new IntamediaCountry() { Code = "026", Name = "امارات عربی متحده", EnglishName = "UNITED ARAB EMIRATES" },
                new IntamediaCountry() { Code = "027", Name = "اندونزی", EnglishName = "INDONESIA" },
                new IntamediaCountry() { Code = "028", Name = "انگلستان(اسکاتلند، ویلز)", EnglishName = "UNITED KINGDOM (BRITAIN)" },
                new IntamediaCountry() { Code = "029", Name = "اوکراین", EnglishName = "UKRAINE" },
                new IntamediaCountry() { Code = "030", Name = "اوگاندا", EnglishName = "UGANDA" },
                new IntamediaCountry() { Code = "031", Name = "ایالات متحده آمریکا", EnglishName = "UNITED STATES" },
                new IntamediaCountry() { Code = "032", Name = "ایتالیا", EnglishName = "ITALY" },
                new IntamediaCountry() { Code = "033", Name = "ایران (جمهوری اسلامی)", EnglishName = "IRAN(ISLAMIC REPUBLIC)" },
                new IntamediaCountry() { Code = "034", Name = "ایرلند", EnglishName = "IRELAND" },
                new IntamediaCountry() { Code = "035", Name = "ایسلند", EnglishName = "ICELAND" },
                new IntamediaCountry() { Code = "036", Name = "باربادوس", EnglishName = "BARBADOS" },
                new IntamediaCountry() { Code = "037", Name = "باهاماس", EnglishName = "BAHAMAS" },
                new IntamediaCountry() { Code = "038", Name = "بحرین", EnglishName = "BAHREIN" },
                new IntamediaCountry() { Code = "039", Name = "برزیل", EnglishName = "BRAZIL" },
                new IntamediaCountry() { Code = "040", Name = "برونئی", EnglishName = "BRUNEI" },
                new IntamediaCountry() { Code = "041", Name = "بلژیک", EnglishName = "BELGIUM" },
                new IntamediaCountry() { Code = "042", Name = "بلغارستان", EnglishName = "BULGARIA" },
                new IntamediaCountry() { Code = "043", Name = "بلاروس(روسیه سفید)", EnglishName = "BELARUS" },
                new IntamediaCountry() { Code = "044", Name = "بلیز", EnglishName = "BELIZE" },
                new IntamediaCountry() { Code = "045", Name = "بنگلادش", EnglishName = "BANGLADESH" },
                new IntamediaCountry() { Code = "046", Name = "بنین", EnglishName = "BENIN" },
                new IntamediaCountry() { Code = "047", Name = "بوتان", EnglishName = "BHUTAN" },
                new IntamediaCountry() { Code = "048", Name = "بوتسوانا", EnglishName = "BOTSWANA" },
                new IntamediaCountry() { Code = "049", Name = "بورکینافاسو", EnglishName = "BURKINA FASO" },
                new IntamediaCountry() { Code = "050", Name = "بوروندی", EnglishName = "BURUNDI" },
                new IntamediaCountry() { Code = "051", Name = "بوسنی وهرزگوین", EnglishName = "BOSNIA HERZEGOWINA" },
                new IntamediaCountry() { Code = "052", Name = "بولیوی", EnglishName = "BOLIVIA" },
                new IntamediaCountry() { Code = "053", Name = "پاپوا، گینه نو", EnglishName = "PAPUA NEW GUINEA" },
                new IntamediaCountry() { Code = "054", Name = "پاراگوئه", EnglishName = "PARAGUAY" },
                new IntamediaCountry() { Code = "055", Name = "پاکستان", EnglishName = "PAKISTAN" },
                new IntamediaCountry() { Code = "056", Name = "پاناما", EnglishName = "PANAMA" },
                new IntamediaCountry() { Code = "057", Name = "پرتغال", EnglishName = "PORTUGAL" },
                new IntamediaCountry() { Code = "058", Name = "پرو", EnglishName = "PERU" },
                new IntamediaCountry() { Code = "059", Name = "تاجیکستان", EnglishName = "TADZHIKISTAN" },
                new IntamediaCountry() { Code = "060", Name = "تانزانیا", EnglishName = "TANZANIA" },
                new IntamediaCountry() { Code = "061", Name = "تایلند", EnglishName = "TAILAND" },
                new IntamediaCountry() { Code = "062", Name = "تایوان", EnglishName = "TAIWAN" },
                new IntamediaCountry() { Code = "063", Name = "ترکمنستان", EnglishName = "TURKMENISTAN" },
                new IntamediaCountry() { Code = "064", Name = "ترکیه", EnglishName = "TURKEY" },
                new IntamediaCountry() { Code = "065", Name = "ترینیدادوتوباکو", EnglishName = "TRINIDAD & TOBAGO" },
                new IntamediaCountry() { Code = "066", Name = "توگو", EnglishName = "TOGO" },
                new IntamediaCountry() { Code = "067", Name = "تونس", EnglishName = "TUNESIA" },
                new IntamediaCountry() { Code = "068", Name = "تونگا", EnglishName = "TONGA" },
                new IntamediaCountry() { Code = "069", Name = "تووالو", EnglishName = "TOVALO" },
                new IntamediaCountry() { Code = "070", Name = "جامائیکا", EnglishName = "JAMAICA" },
                new IntamediaCountry() { Code = "071", Name = "جیبوتی", EnglishName = "DJIBOUTI" },
                new IntamediaCountry() { Code = "072", Name = "چاد", EnglishName = "CHAD" },
                new IntamediaCountry() { Code = "073", Name = "چک", EnglishName = "CZECH" },
                new IntamediaCountry() { Code = "074", Name = "چین", EnglishName = "CHINA" },
                new IntamediaCountry() { Code = "075", Name = "دانمارک", EnglishName = "DENMARK" },
                new IntamediaCountry() { Code = "076", Name = "دومینیکا", EnglishName = "DOMINICA" },
                new IntamediaCountry() { Code = "077", Name = "دومینیکن", EnglishName = "DOMINICAN REPUBLIC" },
                new IntamediaCountry() { Code = "078", Name = "رواندا", EnglishName = "RWANDA" },
                new IntamediaCountry() { Code = "079", Name = "روسیه(فدراتیو)", EnglishName = "RUSSIAN FEDERATION(RUS)" },
                new IntamediaCountry() { Code = "080", Name = "رومانی", EnglishName = "ROMANI" },
                new IntamediaCountry() { Code = "081", Name = "زامبیا", EnglishName = "ZAMBIA" },
                new IntamediaCountry() { Code = "082", Name = "نیوزلند(زلاند نو)", EnglishName = "NEW ZEALAND" },
                new IntamediaCountry() { Code = "083", Name = "زیمبابوه", EnglishName = "ZIMBABWE" },
                new IntamediaCountry() { Code = "084", Name = "ژاپن", EnglishName = "JAPAN" },
                new IntamediaCountry() { Code = "085", Name = "ساحل عاج", EnglishName = "IVORY COAST" },
                new IntamediaCountry() { Code = "086", Name = "ساموآی غربی", EnglishName = "SAMOA(WESTERN" },
                new IntamediaCountry() { Code = "087", Name = "سان مارینو", EnglishName = "SAN MARINO" },
                new IntamediaCountry() { Code = "088", Name = "سائوتومه وپرنسیپ", EnglishName = "SAO TOME & PRINCIPE" },
                new IntamediaCountry() { Code = "089", Name = "سریلانکا", EnglishName = "SRILANKA" },
                new IntamediaCountry() { Code = "090", Name = "سولومون", EnglishName = "SOLOMON(ISLANDS" },
                new IntamediaCountry() { Code = "091", Name = "سنت کیتس و نویس", EnglishName = "SAINT KEATS & NOICE" },
                new IntamediaCountry() { Code = "092", Name = "سنت لوسیا", EnglishName = "SANTA LUCIA" },
                new IntamediaCountry() { Code = "093", Name = "سنت وین سنت وگرنادین", EnglishName = "SAINT VINCENT" },
                new IntamediaCountry() { Code = "094", Name = "سنگاپور", EnglishName = "SINGAPORE" },
                new IntamediaCountry() { Code = "095", Name = "سنگال", EnglishName = "SENEGAL" },
                new IntamediaCountry() { Code = "096", Name = "سوازیلند", EnglishName = "SWASILAND" },
                new IntamediaCountry() { Code = "097", Name = "سودان", EnglishName = "SUDAN" },
                new IntamediaCountry() { Code = "098", Name = "سورینام", EnglishName = "SURINAM" },
                new IntamediaCountry() { Code = "099", Name = "سوریه", EnglishName = "SYRIA" },
                new IntamediaCountry() { Code = "100", Name = "سومالی", EnglishName = "SOMALIA" },
                new IntamediaCountry() { Code = "101", Name = "سوئد", EnglishName = "SWEDEN" },
                new IntamediaCountry() { Code = "102", Name = "سوئیس", EnglishName = "SWITZERLAND" },
                new IntamediaCountry() { Code = "103", Name = "سیشل", EnglishName = "SEYCHELLES" },
                new IntamediaCountry() { Code = "104", Name = "سیرالئون", EnglishName = "SIERRA LEONE" },
                new IntamediaCountry() { Code = "105", Name = "شیلی", EnglishName = "CHILE" },
                new IntamediaCountry() { Code = "106", Name = "صحرای باختری", EnglishName = "WESTERN SAHARA" },
                new IntamediaCountry() { Code = "107", Name = "عراق", EnglishName = "IRAQ" },
                new IntamediaCountry() { Code = "108", Name = "عربستان سعودی", EnglishName = "SAUDI ARABIA" },
                new IntamediaCountry() { Code = "109", Name = "عمان", EnglishName = "OMAN" },
                new IntamediaCountry() { Code = "110", Name = "غنا", EnglishName = "GHANA" },
                new IntamediaCountry() { Code = "111", Name = "فرانسه", EnglishName = "FRANCE" },
                new IntamediaCountry() { Code = "112", Name = "فلسطین", EnglishName = "PALESTINE" },
                new IntamediaCountry() { Code = "113", Name = "فنلاند", EnglishName = "FINLAND" },
                new IntamediaCountry() { Code = "114", Name = "فیجی", EnglishName = "FIJI" },
                new IntamediaCountry() { Code = "115", Name = "فیلیپین", EnglishName = "PHILIPINES" },
                new IntamediaCountry() { Code = "116", Name = "قبرس", EnglishName = "CYPRUS" },
                new IntamediaCountry() { Code = "117", Name = "قرقیزستان", EnglishName = "KIRGIZISTAN" },
                new IntamediaCountry() { Code = "118", Name = "قزاقستان", EnglishName = "KAZAKHSTAN" },
                new IntamediaCountry() { Code = "119", Name = "قطر", EnglishName = "QATAR" },
                new IntamediaCountry() { Code = "120", Name = "کاپ  ورد", EnglishName = "CAPVERDE" },
                new IntamediaCountry() { Code = "121", Name = "کاستاریکا", EnglishName = "COSTARICA" },
                new IntamediaCountry() { Code = "122", Name = "کامبوج", EnglishName = "CAMBODIA" },
                new IntamediaCountry() { Code = "123", Name = "کامرون", EnglishName = "CAMEROUN" },
                new IntamediaCountry() { Code = "124", Name = "کانادا", EnglishName = "CANADA" },
                new IntamediaCountry() { Code = "125", Name = "کروواسی", EnglishName = "CROATIA" },
                new IntamediaCountry() { Code = "126", Name = "کره جنوبی", EnglishName = "KOREA(SOUTH)" },
                new IntamediaCountry() { Code = "127", Name = "کره شمالی", EnglishName = "KOREA(NORTH)" },
                new IntamediaCountry() { Code = "128", Name = "کلمبیا", EnglishName = "COLOMBIA" },
                new IntamediaCountry() { Code = "129", Name = "کنگو", EnglishName = "CONGO" },
                new IntamediaCountry() { Code = "130", Name = "کنگو(زئیر)", EnglishName = "CONGO (ZAIRE)" },
                new IntamediaCountry() { Code = "131", Name = "کنیا", EnglishName = "KENYA" },
                new IntamediaCountry() { Code = "132", Name = "کوبا", EnglishName = "CUBA" },
                new IntamediaCountry() { Code = "133", Name = "کومورو(قمر)", EnglishName = "COMOROS (QAMAR)" },
                new IntamediaCountry() { Code = "134", Name = "کویت", EnglishName = "KUWAIT" },
                new IntamediaCountry() { Code = "135", Name = "کیریباتی", EnglishName = "KIRIBATI" },
                new IntamediaCountry() { Code = "136", Name = "گابون", EnglishName = "GABON" },
                new IntamediaCountry() { Code = "137", Name = "گامبیا", EnglishName = "GAMBIA" },
                new IntamediaCountry() { Code = "138", Name = "گرجستان", EnglishName = "GEORGIA" },
                new IntamediaCountry() { Code = "139", Name = "گرنادا", EnglishName = "GRENADA" },
                new IntamediaCountry() { Code = "140", Name = "گواتمالا", EnglishName = "GUATEMALA" },
                new IntamediaCountry() { Code = "141", Name = "گویان", EnglishName = "GUYANA" },
                new IntamediaCountry() { Code = "142", Name = "گینه", EnglishName = "GUINEA" },
                new IntamediaCountry() { Code = "143", Name = "گینه استوائی", EnglishName = "EQUATORIAL GUINEA" },
                new IntamediaCountry() { Code = "144", Name = "گینه بیسائو", EnglishName = "GUINEABISSAO" },
                new IntamediaCountry() { Code = "145", Name = "لائوس", EnglishName = "LAOS" },
                new IntamediaCountry() { Code = "146", Name = "لبنان", EnglishName = "LEBANON" },
                new IntamediaCountry() { Code = "147", Name = "لیتوانی", EnglishName = "LITHUANIA" },
                new IntamediaCountry() { Code = "148", Name = "لسوتو", EnglishName = "LESOTHO" },
                new IntamediaCountry() { Code = "149", Name = "لوکزامبورگ", EnglishName = "LUXEMBOURG" },
                new IntamediaCountry() { Code = "150", Name = "لهستان", EnglishName = "POLAND" },
                new IntamediaCountry() { Code = "151", Name = "لیبریا", EnglishName = "LIBERIA" },
                new IntamediaCountry() { Code = "152", Name = "لیبی", EnglishName = "LIBYA" },
                new IntamediaCountry() { Code = "153", Name = "لتونی", EnglishName = "LETONI" },
                new IntamediaCountry() { Code = "154", Name = "لیختن اشتاین", EnglishName = "LIECHTENSTEIN" },
                new IntamediaCountry() { Code = "155", Name = "ماداگاسکار", EnglishName = "MADAGASCAR" },
                new IntamediaCountry() { Code = "156", Name = "مارشال{جزایر}", EnglishName = "MARSHAL (ISLANDS)" },
                new IntamediaCountry() { Code = "157", Name = "مالاوی", EnglishName = "MALAWI" },
                new IntamediaCountry() { Code = "158", Name = "مالت", EnglishName = "MALTA" },
                new IntamediaCountry() { Code = "159", Name = "مالدیو", EnglishName = "MALDIVES" },
                new IntamediaCountry() { Code = "160", Name = "مالزی", EnglishName = "MALAYSIA" },
                new IntamediaCountry() { Code = "161", Name = "مالی", EnglishName = "MALI" },
                new IntamediaCountry() { Code = "162", Name = "مجارستان", EnglishName = "HUNGARY" },
                new IntamediaCountry() { Code = "163", Name = "مصر", EnglishName = "EGYPT" },
                new IntamediaCountry() { Code = "164", Name = "مغرب (مراکش)", EnglishName = "MAGHREB (MOROCCO)" },
                new IntamediaCountry() { Code = "165", Name = "مغولستان", EnglishName = "MONGOLIA" },
                new IntamediaCountry() { Code = "166", Name = "مقدونیه", EnglishName = "MACEDONIA" },
                new IntamediaCountry() { Code = "167", Name = "مکزیک", EnglishName = "MEXICO" },
                new IntamediaCountry() { Code = "168", Name = "موریتانی", EnglishName = "MAURITANIA" },
                new IntamediaCountry() { Code = "169", Name = "موریس", EnglishName = "MAURITIUS" },
                new IntamediaCountry() { Code = "170", Name = "موزامبیک", EnglishName = "MOZAMBIQUE" },
                new IntamediaCountry() { Code = "171", Name = "مولداوی", EnglishName = "MOLDAVIA" },
                new IntamediaCountry() { Code = "172", Name = "موناکو", EnglishName = "MONACO" },
                new IntamediaCountry() { Code = "173", Name = "میانمار(برمه)", EnglishName = "MYANMAR (BURMA)" },
                new IntamediaCountry() { Code = "174", Name = "میکرونزی", EnglishName = "MICRONESIA" },
                new IntamediaCountry() { Code = "175", Name = "نامیبیا", EnglishName = "NAMIBIA" },
                new IntamediaCountry() { Code = "176", Name = "نائورو", EnglishName = "NAURO" },
                new IntamediaCountry() { Code = "177", Name = "نپال", EnglishName = "NEPAL" },
                new IntamediaCountry() { Code = "178", Name = "نروژ", EnglishName = "NORWAY" },
                new IntamediaCountry() { Code = "179", Name = "نیجر", EnglishName = "NIGER" },
                new IntamediaCountry() { Code = "180", Name = "نیجریه", EnglishName = "NIGERIA" },
                new IntamediaCountry() { Code = "181", Name = "نیکاراگوا", EnglishName = "NICARAGUA" },
                new IntamediaCountry() { Code = "182", Name = "واتیکان", EnglishName = "VATICAN" },
                new IntamediaCountry() { Code = "183", Name = "وانواتو", EnglishName = "VANUATU" },
                new IntamediaCountry() { Code = "184", Name = "ونزوئلا", EnglishName = "VENEZUELA" },
                new IntamediaCountry() { Code = "185", Name = "ویتنام", EnglishName = "VIETNAM" },
                new IntamediaCountry() { Code = "186", Name = "هائیتی", EnglishName = "HAITI" },
                new IntamediaCountry() { Code = "187", Name = "هلند", EnglishName = "NETHERLANDS" },
                new IntamediaCountry() { Code = "188", Name = "هند", EnglishName = "INDIA" },
                new IntamediaCountry() { Code = "189", Name = "هندوراس", EnglishName = "HONDURAS" },
                new IntamediaCountry() { Code = "190", Name = "یمن", EnglishName = "YEMEN" },
                new IntamediaCountry() { Code = "191", Name = "یوگسلاوی", EnglishName = "YUGOSLAVIA" },
                new IntamediaCountry() { Code = "192", Name = "یونان", EnglishName = "GREECE" },
                new IntamediaCountry() { Code = "193", Name = "سازمان ملل متحد", EnglishName = "UN" },
                new IntamediaCountry() { Code = "194", Name = "کوزوو", EnglishName = "KOSOVO" },
                new IntamediaCountry() { Code = "195", Name = "پورتوریکو", EnglishName = "PEURTORICO" },
                new IntamediaCountry() { Code = "197", Name = "اتریش", EnglishName = "AUSTRIA" },
                new IntamediaCountry() { Code = "198", Name = "چندملیتی", EnglishName = "MULTINATIONAL" },
                new IntamediaCountry() { Code = "199", Name = "هنگ کنگ", EnglishName = "HONG KONG" },
                new IntamediaCountry() { Code = "200", Name = "سایر", EnglishName = "ETC" },
                new IntamediaCountry() { Code = "201", Name = "صربستان ومونته نگرو", EnglishName = "SERBIA AND MONTENEGRO" },
                new IntamediaCountry() { Code = "202", Name = "آنگویلا", EnglishName = "Anguilla" },
                new IntamediaCountry() { Code = "203", Name = "آنتیل هلند", EnglishName = "Netherlands Antilles" },
                new IntamediaCountry() { Code = "204", Name = "جنوبگان", EnglishName = "Antarctica" },
                new IntamediaCountry() { Code = "205", Name = "ساموآی آمریکا", EnglishName = "American Samoa" },
                new IntamediaCountry() { Code = "206", Name = "آروبا", EnglishName = "Aruba" },
                new IntamediaCountry() { Code = "207", Name = "جزایر الند", EnglishName = "Åland" },
                new IntamediaCountry() { Code = "208", Name = "جزیره بووه", EnglishName = "Bouvet Island" },
                new IntamediaCountry() { Code = "209", Name = "جزایر کوکوس", EnglishName = "Cocos (Keeling) Islands" },
                new IntamediaCountry() { Code = "210", Name = "جمهوری کنگو", EnglishName = "Republic of the Con" },
                new IntamediaCountry() { Code = "211", Name = "ساحل عاج", EnglishName = "Côte d'Ivoire" },
                new IntamediaCountry() { Code = "212", Name = "جزایر کوک", EnglishName = "Cook Islands" },
                new IntamediaCountry() { Code = "213", Name = "جزیره کریسمس", EnglishName = "Christmas Island" },
                new IntamediaCountry() { Code = "214", Name = "جزایر فارو", EnglishName = "Faroe Islands" },
                new IntamediaCountry() { Code = "215", Name = "گویان فرانسه", EnglishName = "French Guiana" },
                new IntamediaCountry() { Code = "216", Name = "جبل طارق", EnglishName = "Gibraltar" },
                new IntamediaCountry() { Code = "217", Name = "گرینلند", EnglishName = "Greenland" },
                new IntamediaCountry() { Code = "218", Name = "جزیره گوادلوپ", EnglishName = "Guadeloupe" },
                new IntamediaCountry() { Code = "219", Name = "جورجیای جنوبی و جزایر ساندویچ جنوبی", EnglishName = "South Georgia and the South Sandwich Islands" },
                new IntamediaCountry() { Code = "220", Name = "گوآم", EnglishName = "Guam" },
                new IntamediaCountry() { Code = "221", Name = "قلمرو اقیانوس هند بریتانیا", EnglishName = "British Indian Ocean Territory" },
                new IntamediaCountry() { Code = "222", Name = "ماکائو", EnglishName = "Macau" },
                new IntamediaCountry() { Code = "223", Name = "جزایر ماریانای شمالی", EnglishName = "Northern Mariana Islands" },
                new IntamediaCountry() { Code = "224", Name = "مونتسرات", EnglishName = "Montserrat" },
                new IntamediaCountry() { Code = "225", Name = "کالدونیای جدید", EnglishName = "New Caledonia" },
                new IntamediaCountry() { Code = "226", Name = "نیووی", EnglishName = "Niue" },
                new IntamediaCountry() { Code = "227", Name = "سنت پیر و ماژلان", EnglishName = "Saint-Pierre and Miquelon" },
                new IntamediaCountry() { Code = "228", Name = "پالائو", EnglishName = "Palau" },
                new IntamediaCountry() { Code = "229", Name = "رئونیون", EnglishName = "Réunion" },
                new IntamediaCountry() { Code = "230", Name = "سینت هلینا", EnglishName = "Saint Helena" },
                new IntamediaCountry() { Code = "231", Name = "اتحاد جماهیر شوروی", EnglishName = "Soviet Union" },
                new IntamediaCountry() { Code = "232", Name = "جزایر تورکس و کایکوس", EnglishName = "Turks and Caicos Islands" },
                new IntamediaCountry() { Code = "233", Name = "سرزمین‌های قطب جنوب و جنوبی فرانسه", EnglishName = "French Southern and Antarctic Lands" },
                new IntamediaCountry() { Code = "234", Name = "توکلائو", EnglishName = "Tokelau" },
                new IntamediaCountry() { Code = "235", Name = "تیمور شرقی", EnglishName = "East Timor" },
                new IntamediaCountry() { Code = "236", Name = "تیمور شرقی", EnglishName = "East Timor" },
                new IntamediaCountry() { Code = "237", Name = "انگلستان", EnglishName = "United Kingdom" },
                new IntamediaCountry() { Code = "238", Name = "جزایر ویرجین انگلستان", EnglishName = "British Virgin Islands" },
                new IntamediaCountry() { Code = "239", Name = "جزایر ویرجین ایالات متحده", EnglishName = "United States Virgin Islands" },
                new IntamediaCountry() { Code = "240", Name = "مایوت", EnglishName = "Mayotte" },
                new IntamediaCountry() { Code = "241", Name = "زائیر", EnglishName = "Zaire" },
                    ];
            }
        }
    }
}
